### ISSUE TITLE
canvas-prebuilt / node-pre-gyp doesn't build on node 12

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#1009]
We won't be able to build Paint if we update Node

Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-darwin-x64.tar.gz

**Comment by adroitwhiz** [comment]
See also the [`canvas-prebuilt` deprecation notice](https://github.com/node-gfx/node-canvas-prebuilt):

> **NOTE:** the `canvas-prebuilt` package is deprecated. As of version 2, [`canvas`](https://github.com/Automattic/node-canvas) itself bundles prebuilt versions from this repo. Install by running
> ```
> npm install --save canvas
> ```
> …and use `canvas` as usual.
