### ISSUE TITLE
Fix the little thumbnails becoming weird after you edit costumes with the paint editor

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#101]

**Comment by fsih** [comment]
"When you start editing a sprite, the sprite thumbnail is resized so that the sprite looks tiny in it", from Julia during playtest

**Comment by fsih** [comment]
@cwillisf I heard you might be working on this?

**Comment by cwillisf** [comment]
I'm going to be working on LLK/scratch-gui#762, which seems like it might be related to or even the root cause of this issue. I'll let you know how it goes...
