### ISSUE TITLE
There's some room between the scrollbars and the canvas edges where you can interact with the canvas

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-paint#1011]
### Expected Behavior

When you position your mouse around the scrollbar and drag, one of two things should happen:
- You drag the scrollbar
- Your mouse is off the edge of the canvas, and nothing happens

### Actual Behavior

There are a few pixels between the scrollbar and the edge of the canvas where you can accidentally do things that interact with the canvas:
![Peek 2020-04-22 13-13](https://user-images.githubusercontent.com/25993062/80012341-2e4fcb00-849b-11ea-96a7-34a53a0542aa.gif)

This is related to #611 somewhat-- because the scrollbars are so small, I often aim my mouse more towards the canvas edges than the center of the scrollbar, so as to avoid not getting close enough to the scrollbar and interacting with the canvas.

### Steps to Reproduce

1. Position the mouse in between the scrollbar and the edge of the canvas
2. Notice that dragging your mouse interacts with the canvas instead of the scrollbar

### Operating System and Browser

All

**Comment by fsih** [comment]
Let's start by making the margin between the scrollbar and the edge of the paint editor count as part of the scrollbar hit area
