### ISSUE TITLE
Does Not Properly Support Sphere SVG

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-paint#105]
### Reproduce
Load ```sphrere.svg``` into a scratch project and load it into the 3.0 editor. Open the costume editor and try editing it.
### Image
![img](https://user-images.githubusercontent.com/17478432/32022984-fbccccae-b9a5-11e7-9fa4-e13aa7407366.PNG)
### Sphere.svg
https://wpollock.com/SVG/sphere.svg

**Comment by fsih** [comment]
It might be https://github.com/paperjs/paper.js/issues/1632
