### ISSUE TITLE
Paint editor grid contrast is too low

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#1082]
### Expected Behavior
We lowered the contrast of the checkerboard in the background of the paint editor to reduce eye-strain, but now there are complaints that the contrast is too low.

### Actual Behavior
There are reports on the forums that it is hard to see when painting with white, or that the grid lines appear to be "missing" on some devices

### Steps to Reproduce
View paint editor
<img width="665" alt="Screen Shot 2020-05-24 at 23 04 16" src="https://user-images.githubusercontent.com/2855464/82774454-ebbf3c80-9e12-11ea-98dc-3747a48309b6.png">

### Operating System and Browser
all

**Comment by Explosion-Scratch** [comment]
Yes, before the stretchy paint update the grid had a little bit of a higher contrast to the background. This should be fixed.
