### ISSUE TITLE
Dragging shapes around adds pointless extra attributes to exported SVG

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-paint#1099]
### Expected Behavior

Exported SVGs should not contain any unnecessary attributes/data

### Actual Behavior

In vector mode, if you drag an item around in the paint editor, `data-paper-data="{&quot;origPos&quot;:null}"` will be added to its corresponding exported SVG element.

### Steps to Reproduce

1. Ungroup the default cat costume
2. Drag some of its shapes around
3. Export the costume
4. Open the exported SVG in a text editor and search for `data-paper-data`
5. Notice that it appears on every element you dragged around in the paint editor

### Operating System and Browser

All

**Comment by Explosion-Scratch** [comment]
Does this have to do with another bug where draggeming an object in vector creates a duplicate reshape point directly on top of the old one? If so, to see this effect make a large outline on the object before ddragging and you will see that sometimes it makes a spike in the outline there.

**Comment by adroitwhiz** [comment]
> Does this have to do with another bug where draggeming an object in vector creates a duplicate reshape point directly on top of the old one?

No; this is unrelated.

**Comment by Explosion-Scratch** [comment]
@androitwhiz Oh, lol should I make a new issues for that then?

**Comment by adroitwhiz** [comment]
No, it already exists: https://github.com/LLK/scratch-paint/issues/691 (or https://github.com/LLK/scratch-paint/issues/996)

**Comment by Explosion-Scratch** [comment]
@androitwhiz.  I think it is more like #996, this happens when you drag a vector _object_ not when clicking near a reshape point.

**Comment by adroitwhiz** [comment]
This is still happening if you rotate shapes; `origRot` is still serialized into `data-paper-data`
