### ISSUE TITLE
Scratch-paint license clarity

### ISSUE THREAD

**Issue by ghost** [LLK/scratch-paint#1125]
### Expected Behavior

Github indicates this project under BSD 3-clause license while the LICENSE file (develop branch) seems to be MIT.

The reason I'm interested in this is because I would like to reuse some of nice tool icons in our applications. Could someone advise if my understanding about including the MIT license file and attribution file in our binaries are sufficient?

Thanks.

### Actual Behavior

Both Github project and license file should reflect the same license.

### Steps to Reproduce

See https://github.com/LLK/scratch-paint/blob/develop/LICENSE

### Operating System and Browser

Any browser.

**Comment by apple502j** [comment]
I think license file is BSD - [this is MIT license](https://opensource.org/licenses/MIT).
"Massachusetts Institute of Technology" is copyright holder

**Comment by ghost** [comment]
Thanks @apple502j. This can be now closed as we switch to fontawesome now. Sorry for the noise.
