### ISSUE TITLE
Ungrouping can deselect items

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#1153]
### Expected Behavior
Ungrouped items stay selected

### Actual Behavior
Some of the sub items become unselected
![keyboard shortcut](https://user-images.githubusercontent.com/2855464/85912164-820ec580-b7f8-11ea-8ee5-d869aaf9c5a8.gif)

### Steps to Reproduce
Select the default cat and hit ungroup

### Operating System and Browser
Mac Chrome

**Comment by Jacco** [comment]
Hm the comment with `ungroupSelection` specifically mentions deselecting "other" items.
 
``` js
/**
 * Ungroups the selected items. Other items are deselected and the ungrouped items are selected.
 *
 * @param {!function} clearSelectedItems Function to clear Redux state's selected items
 * @param {!function} setSelectedItems Function to set Redux state with new list of selected items
 * @param {!function} onUpdateImage Function to let listeners know that SVG has changed.
 */
```

**Comment by fsih** [comment]
Ohhh I see what's happening. Thanks for the link! We'll probably need to give this issue a bit more thought then.

**Comment by fsih** [comment]
Talked to design, and we agreed that we should change the ungroup behavior to not deselect 👍
