### ISSUE TITLE
Eraser inverts color/holes

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#119]
![eraserbug](https://user-images.githubusercontent.com/2855464/32118111-90146916-bb1e-11e7-95ab-6f7fb0241a50.gif)

This one is probably in paper.js. If you make a shape with a tail and a loop and subtract a shape that goes through both the tail and the loop, part of the path gets inverted.

**Comment by AmazingMech2418** [comment]
I actually found that in https://github.com/LLK/scratch-gui/issues/1257 .
