### ISSUE TITLE
Erasing through path with holes doesn't act right

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-paint#120]
1. Make a donut with the brush tool.

2a. Erase from outside the donut through to the other side of the donut.
![erase-bug1](https://user-images.githubusercontent.com/654102/32118148-ab559970-bb1e-11e7-8014-9096fbc1e8c3.gif)

2b. Erase from inside the donut to outside the donut.
![erase-bug2](https://user-images.githubusercontent.com/654102/32118149-ab6731e4-bb1e-11e7-8317-3a64ef86a9a0.gif)

**Comment by AmazingMech2418** [comment]
I just realized a dot on the Scratch Cat's tail. Could that be another bug or was it added?

**Comment by ericrosenbaum** [comment]
We saw a problem that may be the same bug in the knight, monet, and spaceship costumes. Here's the knight:

![eraser-bug-knight](https://user-images.githubusercontent.com/567844/37737410-03d82842-2d2a-11e8-836c-b235ff8b683a.gif)

**Comment by fsih** [comment]
Bumping to critical since this comes up all the time in playtests. Many costumes have solid outlines, which are shapes with a hole.
