### ISSUE TITLE
Deleting costume while an object is selected in canvas does something unexpected

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-paint#121]
**What happens:**
![delete costume with selected object](https://user-images.githubusercontent.com/3409578/32119376-0b301cae-bb23-11e7-88e9-3c8327476b12.gif)

**Repro:** 
1. Select the cat
2. Delete the costume with the selected cat
3. WAT?

**What should happen:**
When the costume is deleted, the next costume in the list should become selected, and the canvas should display the content of the newly selected costume. See 2.0 functionality.

**Comment by fsih** [comment]
Fixed by https://github.com/LLK/scratch-gui/commit/c177706a121c8bd0c6c9271eca5c37a294f0a5ed
