### ISSUE TITLE
The second color of the gradient outline can appear to be mixed

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#1215]
### Expected Behavior
When drawing one thing (e.g. a line), the color should not show "mixed", and if it's a gradient, neither color should snow "mixed"

### Actual Behavior
The second color of the gradient outline can appear to be mixed

### Steps to Reproduce
![gradient weirdness 4](https://user-images.githubusercontent.com/2855464/89722950-18b8cf80-d9be-11ea-8841-79d8ba85a449.gif)

### Operating System and Browser
all

**Comment by BryceLTaylor** [comment]
Fixed by #1211
