### ISSUE TITLE
The stroke width looks larger on the stage, than in the Paint Editor

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#129]
from Eric s

**Comment by jwzimmer-zz** [comment]
![pasted image at 2017_10_27 02_17 pm](https://user-images.githubusercontent.com/1320456/32123936-1ac32b0a-bb34-11e7-82f9-b644acae5c82.png)

**Comment by carljbowman** [comment]
Tracking in https://github.com/LLK/scratch-paint/issues/140
