### ISSUE TITLE
Issues With Sprites on Older Projects

### ISSUE THREAD

**Issue by AmazingMech2418** [LLK/scratch-paint#1320]
### Expected Behavior

Sprites in projects such as https://scratch.mit.edu/projects/152427657/ should work exactly as they did years ago.

### Actual Behavior

The sprites have strangely been replaced with question marks that also show up differently than they appear in the paint editor.

### Steps to Reproduce

Go to a project such as https://scratch.mit.edu/projects/152427657/.

### Operating System and Browser

Windows 10 on Chrome

**Note:** I wasn't sure if this should be in scratch-gui or scratch-paint or some other repo, but it seems to be an issue with the new paint editor, so I put it here.

**Comment by DabDatBass** [comment]
Aha! Somebody else has this problem :)

I'm using a macOS on Chrome.

**Comment by fsih** [comment]
Related to the SVG render changes maybe? @BryceLTaylor @cwillisf

**Comment by adroitwhiz** [comment]
This may be https://github.com/cure53/DOMPurify/issues/492

**Comment by BryceLTaylor** [comment]
The part where the question mark image appears differently on the stage than it does in the paint editor is already filed here: https://github.com/LLK/scratch-gui/issues/5187.  I couldn't find an issue specifically about the sprites not loading, though.

**Comment by AmazingMech2418** [comment]
@BryceLTaylor Maybe could it be that the way the SVG costumes were uploaded, they were saved in a way that Scratch 2.0 could read them, but Scratch 3.0 can't?
