### ISSUE TITLE
Shift + Click a node in node editor is wonky

### ISSUE THREAD

**Issue by DabDatBass** [LLK/scratch-paint#1332]
### Expected Behavior

It should act like Shift + Clicking in line tool

### Actual Behavior

It goes bonkers

[EDIT: Sadly I cannot upload any footage]

### Steps to Reproduce

Make a line, then select a node and then hold shift.

### Operating System and Browser

ALL

**Comment by BryceLTaylor** [comment]
@DabDatBass can you describe what you mean by "It goes bonkers"?  Also, do you need to be dragging the node to see the behavior you're describing?  I'm not really sure if I'm seeing what you are describing.

**Comment by DabDatBass** [comment]
It goes bonkers as in the node when shift + clicking makes it go in unexpected places.

**Comment by adroitwhiz** [comment]
I'm pretty sure this is intended behavior--when you shift+drag a node, it will snap to move along the vertical, horizontal, and diagonal axes only.

**Comment by BryceLTaylor** [comment]
@adroitwhiz that is what it sounds like to me.
@DabDatBass Holding shift allows a user to constrain the motion of the node.  If you are close to the node's starting place the constraint can change with small motions, causing the behavior you're seeing.  That may be unexpected for some users, but when making small movements they can always let go of shift.  The constraint is very helpful for users when making larger motions.
