### ISSUE TITLE
Add Copy / Paste mode tools

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#134]
I was told you can hold down alt and then move the object, but I would not have known how to do that
from Julia

**Comment by carljbowman** [comment]
![selection tool - 1024x768](https://user-images.githubusercontent.com/3409578/32228576-f976670c-be24-11e7-85ae-b4af1e3605de.png)

[assets.zip](https://github.com/LLK/scratch-paint/files/1430997/assets.zip)

UI States: 
Chatted with @mewtaylor on states
Initial State (Nothing Selected / Nothing Copied)
- Copy: Disabled
- Paste: Disabled

Path Selected / Nothing Copied
- Copy: Enabled
- Paste: Disabled

Path Selected / Path Copied
- Copy: Enabled
- Paste: Enabled

**Comment by carljbowman** [comment]
Adding @mewtaylor to help with layout.
