### ISSUE TITLE
Exporting a costume with an error exports the "error" costume.

### ISSUE THREAD

**Issue by Ascor8522** [LLK/scratch-paint#1347]
### Expected Behavior

When right-clicking an SVG costume with an error (showing the quesrtion mark on a grey background), the original (broken) SVG costume should be exported, even tho its preview is not available.

### Actual Behavior

The "error" SVG costume (the one with a grey background and a back question mark) is exported.

_In the Scratch Editor:_
![image](https://user-images.githubusercontent.com/17651422/104110215-bf8afa00-52d5-11eb-81f5-d75b4bacd322.png)
_The exported costumed onpened in VSCode:_
![image](https://user-images.githubusercontent.com/17651422/104110219-d29dca00-52d5-11eb-98b9-2f82c7f3be5c.png)
_The original costume fecthed from the CDN during project download:_
![image](https://user-images.githubusercontent.com/17651422/104110327-03323380-52d7-11eb-9f5c-aa3ae3ae775f.png)

### Steps to Reproduce

1. Create a project.
2. Export a falty SVG or wait for it to be corrupted by the Scratch server at some point.
3. Open the costume editor of the corrupted/broken costume.
4. Export the costume by right-clicking it.

### Operating System and Browser

Scratch online.

**Comment by BryceLTaylor** [comment]
The issue described here is definitely a concern, but is really a symptom of a broader problem.  I've opened a new issue to address the broader problem here: https://github.com/LLK/scratch-gui/issues/6838.  I'm going to close this issue since it should be addressed in the designs for the broader issue.
