### ISSUE TITLE
Firefox (stable and nightly) : Bitmaps lose color accuracy / change color when selecting and editing

### ISSUE THREAD

**Issue by tutacat** [LLK/scratch-paint#1402]
### Expected Behavior

Bitmaps preserve pixel color values

### Actual Behavior

Colors turn redder or greener depending on firefox version
(I believe that the issue is with FF graphics, as observed on other sites that do graphics in site, but not 100% sure)

### Steps to Reproduce

1. Open firefox (latest or nightly)
2. Go to Scratch editor (Scratch site or github.io page (affects at least develop and master)
2. (on latest, all sprites have a color display error, fixed in nightly versions)
3. Open the editor, convert to bitmap or make a bitmap
4. Select all or part of the bitmap
5. You can change anything or not
6. Deselect
7. Observe the updated bitmap in the editor and on the canvas
8. The same is observed when using the color picker in the editor or on the canvas

### Operating System and Browser

Intel Graphics (Haswell)
Linux x64 Xorg (xfce4)
Mozilla Firefox 85... and Firefox Nightly 87...

**Comment by adroitwhiz** [comment]
> (I believe that the issue is with FF graphics, as observed on other sites that do graphics in site, but not 100% sure)

So does this happen with other sites as well, or just Scratch?

**Comment by tutacat** [comment]
Close due to firefox profile error

**Comment by tutacat** [comment]
> > (I believe that the issue is with FF graphics, as observed on other sites that do graphics in site, but not 100% sure)
> 
> So does this happen with other sites as well, or just Scratch?

Yes, but I hadn't properly troubleshooted
