### ISSUE TITLE
Add Eyedropper to the Color Picker

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-paint#147]
@fsih reported:
> Need to be able to select same color

She was drawing a purple alpaca and having trouble finding the same color of purple multiple times.

<img width="400" alt="screen shot 2017-10-27 at 15 39 34" src="https://user-images.githubusercontent.com/1320456/32123335-c53f0660-bb31-11e7-80ca-d0944bbd6f87.png">

**Comment by carljbowman** [comment]
Sketch:
![selection tool - transparent - 1024x768](https://user-images.githubusercontent.com/3409578/32243700-7e042550-be4c-11e7-857d-ae87721c95ed.png)

Assets:
[eye-dropper-icon.zip](https://github.com/LLK/scratch-paint/files/1431959/eye-dropper-icon.zip)

Question:
@fsih @paulkaplan @rschamp - Depending on how you all are thinking about the eye dropper from a technical perspective, we could do a couple things to indicate the eyedropper is selected and ready to use: 
1. Change the cursor (when over the canvas) to the "loop" element that @paulkaplan built for picking color from the stage (triggered on the Touching [ Color ] block).
2. Change the cursor (when over the canvas) to an eye-dropper icon.
3. Open to other suggestions...

Let me know if you all have thoughts.

**Comment by carljbowman** [comment]
Assigning over to @mewtaylor 

Sketches based on our discussion with @paulkaplan @fsih yesterday: https://invis.io/HDDDQ2P7W

**Comment by mewtaylor** [comment]
Implemented in #212
