### ISSUE TITLE
NaN values in fill color > color picker

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-paint#153]
@chrisgarrity reported NaN values in the color picker:
> Clicked in the Fill tool, still trying to figure out what happened prior to remove the values. May have been because I had been working on a grouped object. Even though I think I was trying to create a simple shape in a new costume when it happened.
Firefox

<img width="254" alt="screen shot 2017-10-27 at 2 37 45 pm" src="https://user-images.githubusercontent.com/1320456/32123649-08b9a912-bb33-11e7-8f2e-99999e0bcd4d.png">

**Comment by fsih** [comment]
Note: Chris was on Firefox

**Comment by rschamp** [comment]
Repro steps:

1. Make a new costume from the library
2. Choose ball-a (or another with a gradient?)
3. Select the ball
4. Open the color picker

**Comment by chrisgarrity** [comment]
Breaks with importing any sprite with a gradient fill.
