### ISSUE TITLE
Zoom blurs background grid

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-paint#155]
Not super critical, but this isn't the way Scratch 2.0 works - the grid stays sharp when zoomed in there.

Scratch 3.0:

![Blurred grid](https://user-images.githubusercontent.com/9948030/32136987-2984a9a6-bbee-11e7-990e-7b0c8c47459e.png)

Scratch 2.0:

![Sharp grid](https://user-images.githubusercontent.com/9948030/32136995-3ea469ca-bbee-11e7-878a-a5f3d8b087e4.png)

**Comment by Alzter** [comment]
I'd rather it stays sharp so I can see precisely.

**Comment by Kenny2github** [comment]
@Alzter yeah, that's the point of this issue.

**Comment by Jacco** [comment]
Could an svg be used as background here? I made a c# script to create the one below:

Characteristics of this one:
- blockSize 4
- 120 x 90 blocks (since editor is 480x360 I kept 4:3 ratio)
- colors #E5E5E5 on white

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="480px" height="360px" viewBox="0 0 120 90">
    <rect style="stroke:none;fill:rgb(255,255,255)" x="0" y="0" width="120" height="90"/>
	<polygon style="stroke:none;fill:#E5E5E5;fill-rule:evenodd;" points=" 0,0 1,0 1,90 2,90 2,0 3,0 3,90 4,90 4,0 5,0 5,90 6,90 6,0 7,0 7,90 8,90 8,0 9,0 9,90 10,90 10,0 11,0 11,90 12,90 12,0 13,0 13,90 14,90 14,0 15,0 15,90 16,90 16,0 17,0 17,90 18,90 18,0 19,0 19,90 20,90 20,0 21,0 21,90 22,90 22,0 23,0 23,90 24,90 24,0 25,0 25,90 26,90 26,0 27,0 27,90 28,90 28,0 29,0 29,90 30,90 30,0 31,0 31,90 32,90 32,0 33,0 33,90 34,90 34,0 35,0 35,90 36,90 36,0 37,0 37,90 38,90 38,0 39,0 39,90 40,90 40,0 41,0 41,90 42,90 42,0 43,0 43,90 44,90 44,0 45,0 45,90 46,90 46,0 47,0 47,90 48,90 48,0 49,0 49,90 50,90 50,0 51,0 51,90 52,90 52,0 53,0 53,90 54,90 54,0 55,0 55,90 56,90 56,0 57,0 57,90 58,90 58,0 59,0 59,90 60,90 60,0 61,0 61,90 62,90 62,0 63,0 63,90 64,90 64,0 65,0 65,90 66,90 66,0 67,0 67,90 68,90 68,0 69,0 69,90 70,90 70,0 71,0 71,90 72,90 72,0 73,0 73,90 74,90 74,0 75,0 75,90 76,90 76,0 77,0 77,90 78,90 78,0 79,0 79,90 80,90 80,0 81,0 81,90 82,90 82,0 83,0 83,90 84,90 84,0 85,0 85,90 86,90 86,0 87,0 87,90 88,90 88,0 89,0 89,90 90,90 90,0 91,0 91,90 92,90 92,0 93,0 93,90 94,90 94,0 95,0 95,90 96,90 96,0 97,0 97,90 98,90 98,0 99,0 99,90 100,90 100,0 101,0 101,90 102,90 102,0 103,0 103,90 104,90 104,0 105,0 105,90 106,90 106,0 107,0 107,90 108,90 108,0 109,0 109,90 110,90 110,0 111,0 111,90 112,90 112,0 113,0 113,90 114,90 114,0 115,0 115,90 116,90 116,0 117,0 117,90 118,90 118,0 119,0 119,90 120,90 120,89 0,89 0,88 120,88 120,87 0,87 0,86 120,86 120,85 0,85 0,84 120,84 120,83 0,83 0,82 120,82 120,81 0,81 0,80 120,80 120,79 0,79 0,78 120,78 120,77 0,77 0,76 120,76 120,75 0,75 0,74 120,74 120,73 0,73 0,72 120,72 120,71 0,71 0,70 120,70 120,69 0,69 0,68 120,68 120,67 0,67 0,66 120,66 120,65 0,65 0,64 120,64 120,63 0,63 0,62 120,62 120,61 0,61 0,60 120,60 120,59 0,59 0,58 120,58 120,57 0,57 0,56 120,56 120,55 0,55 0,54 120,54 120,53 0,53 0,52 120,52 120,51 0,51 0,50 120,50 120,49 0,49 0,48 120,48 120,47 0,47 0,46 120,46 120,45 0,45 0,44 120,44 120,43 0,43 0,42 120,42 120,41 0,41 0,40 120,40 120,39 0,39 0,38 120,38 120,37 0,37 0,36 120,36 120,35 0,35 0,34 120,34 120,33 0,33 0,32 120,32 120,31 0,31 0,30 120,30 120,29 0,29 0,28 120,28 120,27 0,27 0,26 120,26 120,25 0,25 0,24 120,24 120,23 0,23 0,22 120,22 120,21 0,21 0,20 120,20 120,19 0,19 0,18 120,18 120,17 0,17 0,16 120,16 120,15 0,15 0,14 120,14 120,13 0,13 0,12 120,12 120,11 0,11 0,10 120,10 120,9 0,9 0,8 120,8 120,7 0,7 0,6 120,6 120,5 0,5 0,4 120,4 120,3 0,3 0,2 120,2 120,1 0,1"/>
</svg>
```
I tested this one out and it looks great (doesn't blur).  Do you want a PR with this image replacement?

Here is the script for reference:

```
using System.IO;
using System.Text;

namespace CreateBackground
{
    class Program
    {
        static void Main(string[] args)
        {
            var fillColor = "#E5E5E5";
            var blockWidth = 4;
            var width = 120; // 128; // 18; // 125;
            var height = 90; // 96; // 12; // 100;
            var sb = new StringBuilder();
            var y = 0;
            var x = 0;
            while(x < width)
            {
                sb.Append($" {x},{y}");
                x++;
                sb.Append($" {x},{y}");
                y = (y == 0 ? height : 0);
            }
            y = height - 1;
            x = width;
            while(y > 0)
            {
                sb.Append($" {x},{y}");
                x = (x == 0 ? width : 0);
                sb.Append($" {x},{y}");
                y--;
            }
            var template = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\r\n" +
                           $"<svg version=\"1.1\" id=\"Layer_1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"{width * blockWidth}px\" height=\"{height * blockWidth}px\" viewBox=\"0 0 {width} {height}\">" +
                           $"    <rect style=\"stroke:none;fill:rgb(255,255,255)\" x=\"0\" y=\"0\" width=\"{width}\" height=\"{height}\"/>" +
                           $"     <polygon style=\"stroke:none;fill:{fillColor};fill-rule:evenodd;\" points=\"{sb.ToString()}\"/>" +
                           "</svg>";
            File.WriteAllText("background.svg", template);
        }
    }
}

```

**Comment by fsih** [comment]
@Jacco Nice, that's a clever way to draw the grid! Please do make a PR.

If you import an SVG for the background, you may need to change `scratch-paint/src/helper/selection.js`'s `getItems` function to prevent it from picking up the grid (you can test by making sure the eraser does not erase the grid.) You can also avoid using SVGs by instantiating the path directly in Paper, using [the pathdata constructor here.](http://paperjs.org/reference/path/#path--pathData)

**Comment by Jacco** [comment]
Maybe making the path directly in Paper would be wise for now.

- I do not know how many squares we want currently.
- It could be that the edges of the squares will be used for a snap to grid
feature
- This (snapping) grid might change dependent on zoom level

I'll first try convert the c# code to Paper js code :-)

Regards, Jacco

**Comment by fsih** [comment]
The grid squares should be 4x4 units. I think there's no need to worry about zoom, since the grid will be zoomed the same way as the drawing, so it's okay to use a static string for pathData.

**Comment by Jacco** [comment]
Ah just created this before I read your comment, let me know if you want this:

```
const _makeBackgroundSVG = function (width, height, blockWidth, color) {
    var x = 0;
    var y = 0;
    var sb = [];
    while (x < width) {
        sb.push(` ${x},${y}`);
        x++;
        sb.push(` ${x},${y}`);
        y = y == 0 ? height : 0;
    }
    y = height - 1;
    x = width;
    while (y > 0) {
        sb.push(` ${x},${y}`);
        x = (x == 0 ? width : 0);
        sb.push(` ${x},${y}`);
        y--;
    }
    return  `data:image/svg+xml;charset=utf-8,
            <svg version="1.1" id="Layer_1" 
                 xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
                 width="${width * blockWidth}px" height="${height * blockWidth}px" viewBox="0 0 ${width} ${height}">
                <rect style="stroke:none;fill:rgb(255,255,255)" x="0" y="0" width="${width}" height="${height}"/>
                <polygon style="stroke:none;fill:${color};fill-rule:evenodd;" points="${sb.join()}"/>"
            </svg>`; 
}
```

I think when zooming in the blockSize could be reduced otherwise the squares get very big. You could gain more fine grained grid snapping that way.

Regards Jacco

**Comment by fsih** [comment]
@Jacco Let's keep the grid squares to 4x4 for now. For snapping and changing the density of the grid on zoom, could you file new issues on this repo describing how they would work? Since they are not in Scratch 2.0, they are considered feature requests, and new features have to go through designers for deciding whether they go in and how they would look. We'll bookmark this code and use it if we decide to make those changes (:

**Comment by Jacco** [comment]
Ok, I will think about posting a feature request :-) I converted to this code:

It uses a path in stead of an SVG:

```
const _makeBackgroundPaper = function (width, height, blockWidth, color) {
    var x = 0;
    var y = 0;
    var sb = [];
    while (x < width) {
        sb.push(new paper.Point(x,y));
        x++;
        sb.push(new paper.Point(x,y));
        y = y == 0 ? height : 0;
    }
    y = height - 1;
    x = width;
    while (y > 0) {
        sb.push(new paper.Point(x,y));
        x = (x == 0 ? width : 0);
        sb.push(new paper.Point(x,y));
        y--;
    }
    var vPath = new paper.Path(sb);
    vPath.fillRule = 'evenodd';
    vPath.fillColor = color;
    return vPath;
}
```

Regards, Jacco

**Comment by Jacco** [comment]
Personally I'd rather have the version above (creating paper.Point instances) then a static string to pathData, since paperjs will most probably split the string into paper.Points also.

Just let me know: would be happy to put a PR online with any of both solutions. 

Regards, Jacco

**Comment by fsih** [comment]
Okay, sure. I thought it would be less work for you, but since you've already converted the SVG code to paper.Path drawing code, let's use that!

Small note: we try to avoid using abbreviations to keep the code more readable, so please expand the name of the variable sb

**Comment by fsih** [comment]
Closed via #368

**Comment by Jacco** [comment]
@fsih I have worked on another "blur" issue with the eye-drop tool. I solved it and can make a pull request of it. Do you want me to make an issue first? Last time I received some criticism about an issue/PR I created.

**Comment by fsih** [comment]
@Jacco Sure, please feel welcome to submit issues. Everyone should feel free to submit issues.

We discourage contributors from working on PRs for issues that aren't marked help-wanted because sometimes they require a lot of design (we want Scratch to be consistent and beginner friendly) or can be quite difficult, and we feel bad making someone to go through a lot of work that might not be accepted into the codebase.

I think a good approach is to file issues and mention on the issue that you are interested in fixing the bug. Then we can make sure it's something we do want fixed and that shouldn't be too hard to fix and mark it help-wanted. You can submit PRs for things that aren't help-wanted, but be aware that the chance is much higher that those won't be accepted.

I think you've been finding really good issues and solutions so far though! Thank you for all your help!

**Comment by Jacco** [comment]
@fsih Thanks for the compliment! Very glad to be able to contribute :-)
