### ISSUE TITLE
Holding shift while scroll-wheeling should pan left/right (Windows Chrome)

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-paint#156]
Otherwise, it's impossible to scroll left and right with the scroll wheel. Several other paint editor programs use shift-scrolling as a way to scroll left and right.

(Is there an issue for this in scratch-blocks? Shift-scrolling should also be implemented there, especially if it is here.)

**Comment by paulkaplan** [comment]
Are you trying it with a mouse? It is working for me on mac/chrome. What OS/browser are you on?

**Comment by griffpatch** [comment]
Fails for me on windows chrome... Tried all combinations and they either zoom or scroll up and down.
Could really do with the middle button drag to pan feature?

**Comment by towerofnix** [comment]
Firefox 57.0, on Debian (Testing). Zoom (ctrl+scroll) works, but everything else just scrolls up/down.

**Comment by towerofnix** [comment]
The bug here has to do with Firefox not setting deltaX when you hold shift and scroll - in fact, I can't even scroll horizontally on a page without using the horizontal scroll bar. Holding shift and scrolling this GitHub page when it is very thin does nothing!

I imagine Windows Chrome has the same problem.
