### ISSUE TITLE
Dragging the brush gets laggier the more you do it

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-paint#161]
### Expected behavior
Dragging the paint brush should remain smooth
### Actual behavior
Dragging the _pain_ brush gets laggier and laggier the longer you hold down the mouse
### Steps to reproduce
1. Navigate to https://llk.github.io/scratch-paint/develop
2. Click Brush
3. Click and drag, and keep dragging
4. The dragging gets laggy - the brush jumps around more and farther
### Version info
Chromium 57 Raspbian (Debian Jessie) Desktop

**Comment by towerofnix** [comment]
Can reproduce on Firefox 57.0 / Debian (Testing). Note this isn't a Raspberry Pi! I'm probably on a higher end computer, so, the problem might not be linked to available memory/CPU.

**Comment by Kenny2github** [comment]
I'm not on a Raspberry Pi either - I'm on an Acer laptop running the RPi's operating system. It does wonky things, but it works (until recently, when my USB that contained the OS died).

**Comment by thisandagain** [comment]
Tracking in #23
