### ISSUE TITLE
Add Fill tool

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-paint#165]
## Overview 
The fill tool should function similarly to the 2.0 fill tool: allowing a user to pick a color and then apply that color to Shape Fills and Shape Outlines (Strokes). 

More sketches of the Vector Editor: https://invis.io/HDDDQ2P7W

### Step 1 - Choose the Fill tool
- There are no addtional Mode Tools (tool properties that appear to the right of Outline Width, e.g. Brush Tool > Brush Size) for the Fill Tool
- Like when using the Brush Tool, the Outline properties are disabled

![fill tool - fill tool - 1024x768](https://user-images.githubusercontent.com/3409578/33271798-39c46e58-d356-11e7-928c-fdbb4259ae2e.png)

### Step 2 - Pick a color to apply
![fill tool - color picker - 1024x768](https://user-images.githubusercontent.com/3409578/33272025-ea36068e-d356-11e7-85ad-31bbf77626a4.png)

### Step 3 - Hover over a shape's outline to preview color
- Like the Brush and Eraser tool, the cursor changes when over the canvas. 

![fill tool - hover - preview filling outline - 1024x768](https://user-images.githubusercontent.com/3409578/33272069-0dd8ab82-d357-11e7-94a2-139c98e50937.png)

### Step 4 -  Hover over a shape's fill to preview color
![fill tool - hover - preview filling fill - 1024x768](https://user-images.githubusercontent.com/3409578/33272082-16b43370-d357-11e7-95bc-17c521a2c856.png)

### Step 5 - Click to apply to new color to shape's fill
![fill tool - click - confirm fill fill - 1024x768 copy](https://user-images.githubusercontent.com/3409578/33272160-59a4fcbe-d357-11e7-8cbc-356e8077024a.png)

**Comment by Alzter** [comment]
What about gradients? Can we have a more advanced tool to edit them like the gradient tool in Adobe products?

**Comment by Alzter** [comment]
Also, can you show me how you made those mock-ups? I would like to make some showing my ideas.

**Comment by fsih** [comment]
@carljbowman where can I find the asset for the fill tool icon?

**Comment by carljbowman** [comment]
@fsih - Here you go: [fill.svg.zip](https://github.com/LLK/scratch-paint/files/1559572/fill.svg.zip)
