### ISSUE TITLE
Feature Suggestion: ask to open bitmap images as SVG

### ISSUE THREAD

**Issue by TheAwesome98-Real** [LLK/scratch-paint#1689]
If I load a bitmap image bigger than the canvas into this, it’s scaled down to low resolution. A scratcher playing in full screen mode will see low resolution bitmaps with high resolution SVGs (because scalable). If I load a, say, 1080p bitmap, it should ask:

**Load as vector?**
This image is really big. To keep the resolution, Scratch can load this as a vector.
- [ ] Do not ask this again, and do what I choose as the default action
[Load as vector] [Keep as bitmap]

(you can change the default in the Edit menu)

I can choose keep as bitmap for the current functionality, and click load as vector to load the full image in, and scale the vector down to the canvas size. Scratchers then viewing this in full screen will see a high resolution image.

EDIT: TL,DR: images bigger than canvas are scaled as bitmap, convert to vector and scale them that way (ask user first of course)

**Comment by BryceLTaylor** [comment]
Those limitations are intentional.

**Comment by TheAwesome98-Real** [comment]
How can I work around it then?
