### ISSUE TITLE
When zoomed in, selecting a shape by clicking its border is hard

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-paint#178]
From internal smoke-test, 11/3/17.

I was clicking in the same place to reselect the shape but it wasn't getting re-selected. DD said this may have to do with zoom level + tolerance. I used the circle tool to draw the shape and the selector tool to select the shape and find the points.

The same issue also happens when you are trying to click an individual point to drag it.

![out](https://user-images.githubusercontent.com/1320456/32387023-880e27e0-c099-11e7-829f-7d72e5fcd78a.gif)

**Comment by fsih** [comment]
I can't repro this. I do get this "undraggable" behavior when I try to click near where the handles are though (the little squares, which aren't visible when you haven't selected the shape yet) so I suspect this might have been a manifestation of https://github.com/LLK/scratch-paint/issues/150
![clickstroke](https://user-images.githubusercontent.com/2855464/45631623-4cf11300-ba69-11e8-8ec5-7f9b7877f77f.gif)
Secret handle locations
![image](https://user-images.githubusercontent.com/2855464/45631881-f89a6300-ba69-11e8-98e7-657c457fb7a1.png)
