### ISSUE TITLE
Drag box appears after element is deleted

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-paint#181]
I created a black filled rectangle, and then deleted it. The blue drag box thing stayed, even though the element was gone. It isn't a major bug, but it might be confusing.
#### Before Deleting
![before](http://i.cubeupload.com/v1fwX4.png)
#### After Deleting
I used the delete key to delete
![after](http://i.cubeupload.com/VPqGVk.png)

**Comment by jwzimmer-zz** [comment]
We saw this during the internal smoketest on 11/3 as well.
