### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onMouseDrag' (or 'onMouseUp') of undefined

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-paint#182]
About half of the participants (~3 people) in the internal smoketest on 11/3 ran into this issue, which freezes the paint editor. 

@mewtaylor reported, when trying to drag a selected shape using Select tool, drag/drop on Chrome 62, Mac OSX 10.12:
> I wasn't able to drag the item, even after clicking undo before trying

**Comment by fsih** [comment]
Should be fixed by https://github.com/LLK/scratch-paint/pull/180
If people who hit it could try to repro, that would be cool
