### ISSUE TITLE
You can drag costumes off the paint editor and make them inaccessible

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-paint#183]
Currently, you can't move around the workspace in the Paint Editor very easily. You can scroll within it when you are zoomed in, but when you are zoomed out you cannot expand the size of the workspace. This can lead to a situation where you have positioned part of a costume far enough away from other parts of the costume that you can't see both at the same time, and the only way to move between them is to select both.

We observed this during the internal smoketest on 11/3/17.

**Comment by fsih** [comment]
Currently, the user can draw outside of the paint editor frame, e.g. by moving their drawing outside of what's visible. What should we do in this situation? Should we cut off the drawing? Should we allow the user to continue to zoom out to less than 100% so they can draw arbitrarily large things?

**Comment by fsih** [comment]
We discovered in the playtest today that this causes bugs with how the rotation center is set when the SVG is exported to the renderer. Having parts outside of view can cause the whole sprite to render off-center, which is super confusing.

Note from Julia: people may have thought that dragging pieces off-screen would delete them.

**Comment by fsih** [comment]
@carljbowman what do you think should happen when you drag sprites off the visible area? Should they delete like blocks? Should we add a select all button so that you can fish them back up?

**Comment by fsih** [comment]
I think this is essentially a bug about how to implement https://github.com/LLK/scratch-paint/issues/166 so I'm going to merge it with that
