### ISSUE TITLE
"Winter" backdrop is offset in editor (but not stage)

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-paint#206]
Expected: Backdrops are centered the same way in the editor and on the stage.

Actual: Add the "winter" backdrop (after [this PR](https://github.com/LLK/scratch-gui/pull/975)), and you see it display correctly on the stage but offset in the paint editor:

<img width="1276" alt="screen shot 2017-11-30 at 2 18 18 pm" src="https://user-images.githubusercontent.com/567844/33450419-bb318086-d5d9-11e7-8267-69b7ac8117d0.png">

**Comment by thisandagain** [comment]
I think this is an issue with how some of the old SVG assets are reporting scale and rotation center. Some of them (like this one) go outside the bounding box defined for the SVG. I'll attempt a fix but it would be nice if the paint editor understood what to do in instances like this.

**Comment by fsih** [comment]
I think it's that I'm doing the calculation for where the center is wrong. I had assumed that sprites were defining their centers relative to their own bounding boxes, but this sprite seems to be using somewhere else as its "origin". It's reporting its rotation center as (240, 180) or exactly the middle of the stage size. But its size is (616, 503), much bigger than the stage size. It's getting centered (240, 180) from its top left corner.

How do sprites define their rotation center?

**Comment by thisandagain** [comment]
@fsih It is in the sprite / costume / backdrop definition here:
https://github.com/LLK/scratch-gui/blob/develop/src/lib/libraries/backdrops.json#L151

**Comment by fsih** [comment]
I meant, what point is that point defined relative to? I guess it's not the upper left corner of the SVG.

**Comment by thisandagain** [comment]
Assigning @fsih @paulkaplan and I for discussion. We should sit down and step through this together as it impacts multiple parts of the system (paint, render, libraries, asset creation).

**Comment by fsih** [comment]
I noticed it's also offset in the library:
<img width="478" alt="screen shot 2017-12-28 at 12 19 29" src="https://user-images.githubusercontent.com/2855464/34417981-7f46f97e-ebc9-11e7-826f-c83355b481a0.png">
