### ISSUE TITLE
Increase size of bounding box handles

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-paint#211]
Feedback from playtest. @carljbowman mentioned there is a spec for this in invision.

**Comment by carljbowman** [comment]
Here is an initial sketch. We are balancing making these larger so they are easier to click and not having too big of UI that obscures the artwork. In the sketch below the handles are 8px by 8px, with a 2px drop-shadow. 

![selection tool - 1024x768](https://user-images.githubusercontent.com/3409578/33733735-a965ae66-db58-11e7-9eee-bd94875e9143.png)

Obviously we will need to come up with an alternative solution on touch devices.

**Comment by paulkaplan** [comment]
@fsih is this a straightforward fix? I'd love to have this in before our next workshop if possible.

**Comment by fsih** [comment]
Probably. When is the next workshop?
Those drop-shadows look like translucent circles? What color/opacity are they?

**Comment by carljbowman** [comment]
@fsih - The drop shadows in the sketch are the motion color at 25% opacity. We can dial that in if its too much or too little.

motion primary HEX: #4C97FF (has not opacity)
hsla(215, 100%, 65%, 0.25)
