### ISSUE TITLE
Use zoom-to-fit as the default size for editing a costume

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-paint#216]
When entering the paint-editor with no zoom level set, it would be nice if the zoom level was set to that the costume fills the editor. When switching between costumes in the editor the zoom-level shouldn't change (to support animation).

From observation in a workshop - kids were happier once they had the costume at a zoom level where it was easy to see the handles. Usually that was not the default zoom.

**Comment by paulkaplan** [comment]
@carljbowman @fsih this needs a bit more specification before it can be implemented.

1. We specifically don't reset the view of the paint editor when switching costumes because it makes it hard for people doing animations to have the view constantly reset. So when specifically do you want the view to zoom-to-fit? On sprite change? This is the only complicating part of this, because right now the costume editor doesn't know anything about sprites, just which costume it is loading.
2. How specifically do we want the artwork to fit within the view? I assume not out to the edges, because that is too close, but we should zoom-to-fit tightly and then pull back a bit. This doesn't have to be decided in advance, I can demo a few different options.

**Comment by carljbowman** [comment]
@paulkaplan - Sorry for the delay. Here are some of my initial thoughts.

> 1. We specifically don't reset the view of the paint editor when switching costumes because it makes it hard for people doing animations to have the view constantly reset. So when specifically do you want the view to zoom-to-fit? On sprite change? This is the only complicating part of this, because right now the costume editor doesn't know anything about sprites, just which costume it is loading.

It does sound like this is a bit more complicated than anticipated. I do think it's extremely important to maintain the view state (zoom + scroll position) when navigating costumes within a sprite.

As of now, I could see two paths forward, both of which still require a sprite to define it's own default view state: a zoom level based on a sprite's costume(s) with the largest width and height (scroll position is not relevant in the default state).  

1a. Switching sprites would cause a reset to the default zoom level and scroll position for all of the sprite's costumes. Zooming and scroll would act like (2.0 & 3.0) and be persistent across the sprite's costumes such that we retain the ease of animating.

1b. Sprites would retain their zoom level and scroll position when navigating sprite to sprite and only appear in the default view state when a sprite/costume is added. 

> 2. How specifically do we want the artwork to fit within the view? I assume not out to the edges, because that is too close, but we should zoom-to-fit tightly and then pull back a bit. This doesn't have to be decided in advance, I can demo a few different options.

I agree, it would be great if artwork had some padding around the edges in the default zoom. Would love to hear more of what you are thinking @paulkaplan 

In any case that we use the largest costume width and largest costume height to determine the zoom level that accounts for padding, there is potential for the following issues :
- Sprites that contain costumes that are radically different in size (e.g. 4 small costumes and 1 large costume), the smaller costumes will appear more zoomed out to account for the large costume.
- Costume artwork will always vary in size. This may result in zoom level percentages that are inconsistent across sprites depending on how the zoom UI increments/decrements the zoom. 
- This may be an non-issue as there might be a work around, but dynamically setting a zoom percentage might result in zoom-levels with half-pixels.

**Comment by fsih** [comment]
Blocked on https://github.com/LLK/scratch-paint/issues/166

Since this makes a big visual change to the costumes tab, it should either get in by August or be backlogged to work on next year
