### ISSUE TITLE
Issue filling dog

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#227]
On the https://llk.github.io/scratch-gui/paint-fill-test-branch/
When you try to fill the patch on the back of the dog, it will only fill the outline:
![image](https://user-images.githubusercontent.com/2855464/34124270-3df2dda6-e400-11e7-915c-068e82e2c460.png)

**Comment by rschamp** [comment]
I also saw this issue with the body of Dinosaur1-c:

![image](https://user-images.githubusercontent.com/1512021/34124888-8e3e23a4-e402-11e7-82c1-bdc1a8919ef8.png)

**Comment by fsih** [comment]
The issue is that the compound paths aren't clockwise.
