### ISSUE TITLE
Improve brush tool performance

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#23]
Note: keep this scoped to some easy fixes that help elevate the immediate issue.

**Comment by Kenny2github** [comment]
I'll transfer info from my dupe issue:
Dragging the brush gets laggier and laggier, with the brush jumping around more and more.
Also from @towerofnix:
>Note this isn't a Raspberry Pi! I'm probably on a higher end computer, so, the problem might not be linked to available memory/CPU.
