### ISSUE TITLE
Use Google Fonts for text

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-paint#245]
Scratch currently supports only a few fonts. I think it would be awesome if users could choose from any font on the [Google Fonts website](https://fonts.google.com), which has 848 fonts at the time of writing. In the SVG file, you would put `<?xml-stylesheet type="text/css" href="https://fonts.googleapis.com/css?family=Font name goes here...|If there are multiple fonts use pipes"?>` after the `<xml>` or `<svg>` tag.

**Comment by apple502j** [comment]
No support
China blocks it
