### ISSUE TITLE
Opening paint editor with SVG that contains a numeric group ID causes a crash

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-paint#246]
### Expected
- You should be able to view any vector costume in the paint editor

### Actual
- Fatal exception

### Steps to Reproduce
- Open https://llk.github.io/scratch-gui/#188420400
- Select the sprite "101"
- Switch to paint editor

### OS & Platform
MacOS 10.12.6 | Chrome Version 63.0.3239.84 (Official Build) (64-bit)

**Comment by thisandagain** [comment]
Critical issue has been resolved in https://github.com/LLK/scratch-gui/pull/1159 so I'm removing "critical" and pushing this to the backlog.

**Comment by thisandagain** [comment]
Some background for future: this was caused by the "101-a" costume having a group ID of `101`. This was causing a fatal exception in Paper.js. The immediate issue was resolved by simply renaming the group, but the larger issue with Paper.js still remains.

**Comment by fsih** [comment]
duping to https://github.com/LLK/paper.js/issues/13
