### ISSUE TITLE
Add text tool

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#25]

**Comment by Kenny2github** [comment]
Suggestion: Allow Unicode characters! Currently, for example, to type Chinese text I have to use an external image with *rasterized Chinese characters* and import it. If we could type Unicode characters this would help massively for i18n of Scratch projects.

**Comment by carljbowman** [comment]
## Scratch 2.0
### Functionality
Below is a high-lever overview of the 2.0 text tool's functionally and how text interacts with other tools.

**Text Tool** 

- Primary Tooling
  - Add/Edit text directly in the workspace
  - Uses conventional text editing UI (e.g. highlighting, cursor…)
- Mode Tools
  - Font menu to set font
  - Color picker to set/remove the color for all the text
    - Cannot highlight individual characters and set color
- Key commands
  - Copy / Pasta  (OS hotkeys)
  - Delete (delete key)
- MISC Notes / States
  - Single space text objects cannot exist. More than one space or new lines (returns) can exist
    1. Click to make a new text object
    2. Choose the Select Tool
    3. Drag select the are when you made the text object — No text object

**Select Tool** 
- When text is selected and using bounding box, one can stretch/rotate text in the workspace like any other vector object
  -  The text does not become an expanded shape or rasterized as a result of stretching/rotating. Instead it remains editable text and retains stretch/rotation when editing the text.

**Fill Tool**
- When using the Fill tool, all of the text fills the selected color
  - Cannot Fill individual characters 

## Scratch 3.0 - Phase 1
### Functionality
Below is a high-lever overview of the 3.0 text tool's functionally and how text interacts with other tools. Sketches below to help contextualize. 

**Text Tool**
- Primary Tooling
  - Add/Edit text directly in the workspace
    - Uses conventional text editing UI (e.g. highlighting, cursor…)
    - What happens when you click out of “Text Editing State”?
      - 2.0 has inconsistent behavior: sometimes it creates a new text box, something it just deselects the text entirely, and sometimes it transitions to a “Selected State”
      - 3.0 should transition to a “Selected State” with Text mode tools — **[ Different then 2.0 ]** 
- Mode Tools
  - Font menu to set font
  - Set text size — **[ Different then 2.0 ]** 
  - Color picker to set/remove the color for all the text
    - Cannot highlight individual characters and set color
- Key commands
  - Copy / Pasta  (OS hotkeys) — **There may be dragons here**
  - Delete (delete key)
- MISC Notes / States
  - Empty text and whitespace only objects cannot exist — **[ Different then 2.0 ]** 
    1. Click to make a new text object
    2. Choose the Select Tool
    3. Drag select the are when you made the text object — No text object

**Select Tool**
- When text is selected and using bounding box, one can stretch/rotate text in the workspace like any other vector object
  - The text does not become an expanded shape or rasterized as a result of stretching/rotating. Instead it remains editable text and retains stretch/rotation when editing the text.

**Fill Tool**
- When using the Fill tool, all of the text fills the selected color
  - Cannot Fill individual characters

### Font
For initial prototyping we should use 'Open Sans'. In the future we can add more open source fonts to the list, with special attention to fonts that contain non-latin characters. 

### Sketches

#### 1. Choose Text Tool
![select text tool](https://user-images.githubusercontent.com/3409578/37292192-c7877914-25e6-11e8-893c-1626a74dcfa2.png)

#### 2. Click in artboard to type
![initiating typinating](https://user-images.githubusercontent.com/3409578/37292250-e7e7d73a-25e6-11e8-9082-89aba642871e.png)

#### 3. Empty text object (Text Editing State)
![typinating initiated - empty edit text mode](https://user-images.githubusercontent.com/3409578/37292303-0a3749b0-25e7-11e8-93ed-8aa1297e49d7.png)
If the user clicks away without entering text, the text object should be deleted. This will prevent creating lots of empty (invisible) text objects.

#### 4. Typing (Text Editing State)
![typinating comencing - edit text mode](https://user-images.githubusercontent.com/3409578/37292400-3fc62f9c-25e7-11e8-972e-95d727438c67.png)

#### 5. Begin Highlighting (Text Editing State)
![initiating highlightanarding - edit text mode](https://user-images.githubusercontent.com/3409578/37292481-5347a4e2-25e7-11e8-8787-41b0f8adbbbd.png)

#### 6. Highlighted text selection (Text Editing State)
![highlightanarded - edit text mode](https://user-images.githubusercontent.com/3409578/37292511-5ba77ce8-25e7-11e8-892c-420bdf25838a.png)

#### 7. Typing new Text (Text Editing State)
![typinated - edit text mode](https://user-images.githubusercontent.com/3409578/37292565-7c47b97c-25e7-11e8-90d5-f37510fdd5ad.png)

#### 8. Clicking to transition to selected state
![post-typinating click - transition to selected state](https://user-images.githubusercontent.com/3409578/37292597-8cd400f2-25e7-11e8-81cc-e57d625548b8.png)

#### 9. Stretching text (Selected State)
![stretching - transition to selected state](https://user-images.githubusercontent.com/3409578/37292630-a1c4e828-25e7-11e8-9bbf-ea8cf6b46e77.png)

#### 10. Double click to transition to editing state
![initiating typinating - transition to edit state](https://user-images.githubusercontent.com/3409578/37292706-d8f48b8c-25e7-11e8-80d9-edb4650acb7d.png)

**Comment by fsih** [comment]
When these 2 PRs go in, it should complete phase 1!
We decided not to do font size, since it's confusing what it represents when you can stretch and squash the text.
The next big piece to figure out is fonts.
