### ISSUE TITLE
Vector Editor crashes after a moving an object and selecting a new tool

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-paint#255]
### Info
OS: Windows Pro 10 - V1709 - Build 16299.192
Browser: Microsoft Edge 41.16299.192
Repo: https://llk.github.io/scratch-gui/develop/

### Repro
1. Select a vector object
2. Move the vector object
3. Undo/Redo did not register the object moving (can’t undo) and the canvas checkered pattern disappears.
4. Choosing another Vector tool causes a fatal crash

### Notes
This behavior does not happen in Chrome 63.0.3239.132 on the same OS.

**Comment by carljbowman** [comment]
/cc @thisandagain - Here is an issue that we found in today's smoketest. Wasn't sure if this felt like a blocking issue. It does cause a fatal crash. 

I defer to you on the status of blocking & critical.

**Comment by fsih** [comment]
The problem is in virtual-machine.js updateSvg function, which uses TextEncoder. TextEncoder is not supported on Edge, though apparently it's in development.
https://caniuse.com/#feat=textencoder

**Comment by fsih** [comment]
We use text encoder and decoder all over our repos...

**Comment by thisandagain** [comment]
Looks like there are a few different polyfills available:
https://github.com/inexorabletash/text-encoding
