### ISSUE TITLE
Should we be scientifically correct with dinosaurs?

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-paint#257]
The new "dinosaur3" costume can fly, and therefore is scientifically not a dinosaur. But I can see why younger kids might not understand this...

**Comment by towerofnix** [comment]
Pterosaur! 🎉

**Comment by thisandagain** [comment]
We thought about this but decided that it was too pedantic and would lead to Scratchers having trouble finding the Pterosaur.
