### ISSUE TITLE
All the sprites are ungrouped by default

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-paint#258]
### Expected Behavior
Sprites should be grouped

### Actual Behavior
Not so. They're ungrouped by default.
![See it](https://i.gyazo.com/0e5d282b6bd16b2906e5b5994fb4e5dc.gif)
### Steps to Reproduce
1. Add a sprite.
2. Open Paint Editor.
3. Drag something.
### Operating System and Browser
Windows7 SP1 64bit HomePremium
Firefox 57.0.4

**Comment by fsih** [comment]
This was a small change that we made to make the sprites easier to edit. If you would like to use the sprite as a group, you can select the whole sprite and click the 'group' button at the top

**Comment by apple502j** [comment]
I think new scratchers drag the sprite by mistake and cannot fix...

**Comment by Kenny2github** [comment]
@apple502j that's why the "undo" button is there 😉

**Comment by fsih** [comment]
We have decided based on lots of feedback like this to go back to grouping the sprite by default

**Comment by paulkaplan** [comment]
Fixed by https://github.com/LLK/scratch-paint/pull/407
