### ISSUE TITLE
Point editor doesn't work in some cases

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-paint#259]
It's possible to get into a state where the shape points are highlighted but not editable. Create a shape with the paint tool and fill it. Duplicate the object. Click the point editor - the points are editable; click the select arrow - selection is bounding box; select the point editor - points are solid blue and not editable.

Note: I think I also saw this without duplicating - it happens when switching from selection to point editor -- @chrisgarrity

**Comment by fsih** [comment]
Hi @chrisgarrity, I think I need more detailed repro steps, or a gif. I'm not seeing the issue. Here's what I'm trying:
![pointedit](https://user-images.githubusercontent.com/2855464/35353316-ceea4c1e-0114-11e8-9441-ae6ff1a8ba0b.gif)

In general, a point will be filled in blue during point select if the point is selected. If all the points are dark blue, all of the points are selected. Maybe what you're seeing isn't that point selection isn't working, but that when all the points are selected, when you drag one point, you are dragging all of them. In this state, if you click on one of the points, it should deselect all of the other points.
