### ISSUE TITLE
Eyedropper detects checkerboard background

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-paint#270]
If you use the eyedropper on the background, it picks up the checkerboard pattern.
![image](https://user-images.githubusercontent.com/31634240/35409371-fe97981a-01df-11e8-8e5f-2a2be5aa79d5.png)

**Comment by thisandagain** [comment]
That was actually by design. We'll probably keep this.

**Comment by kyleplo** [comment]
@thisandagain No, I don't mean you can see it, that's OK, but if you click, it selects that color:
![checkerboard](https://user-images.githubusercontent.com/31634240/35462028-4e5ba390-02b8-11e8-9b43-39481163bb07.gif)
