### ISSUE TITLE
Using eyedropper triggers mini-editor

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-paint#276]
Clicking on the color picker's eyedropper tool reveals mini-paint-editor mode.

- Go to https://llk.github.io/scratch-gui/develop/ and select costumes tab.
- Select fill menu, select eye dropper, select a color.
- Click again to dismiss fill menu.
- Mini-editor!

![mini-paint-bug2](https://user-images.githubusercontent.com/567844/35537979-46b72a2e-051a-11e8-876d-a84d7b6437e4.gif)

(forgot to add platform details when I posted this, sorry!)
Mac OS 10.13.2 Chrome 64.0, retina display, external monitor NOT connected

**Comment by paulkaplan** [comment]
Yikes. Confirm I can repro, also on preview.

**Comment by fsih** [comment]
Interesting. I haven't been able to repro at all on Windows (Chrome 63.0.3239.132/Firefox/Edge)

**Comment by paulkaplan** [comment]
I repro'd on mac/chrome, but couldn't repro with mac/safari, so could be a browser/platform thing?

**Comment by fsih** [comment]
I tried on mac/chrome and couldn't repro, develop or preview, Mac 10.12.6  and Chrome 63.0.3239.84 (Also Firefox/Safari)

**Comment by ericrosenbaum** [comment]
I just tested this again and noticed that it only happens when NOT using an external monitor (i.e. when using the laptop's retina display)

**Comment by paulkaplan** [comment]
@ericrosenbaum Oh dear, that sounds like it could be a deep graphics card level issue. Kind of like how we used to see the green flag get patterned across the block workspace. @fsih fwiw I'm on chrome 64. Could be a bug introduced on Chrome 64, which would explain why we haven't seen this previously (seems like it would have come up. chrome 64 came out last week).

**Comment by fsih** [comment]
I reproed it! By upgrading to Chrome 64.0.3282.119 (Mac)

**Comment by fsih** [comment]
I found a bug in your bug report! See lower right corner
![flashing](https://user-images.githubusercontent.com/2855464/35593219-488cdd62-05dd-11e8-93f3-d607fa9ad3d4.gif)

**Comment by fsih** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=807427 on Chrome

**Comment by fsih** [comment]
Fixed in Chrome 65
