### ISSUE TITLE
Stroke width does not get updated when stroke color is changed from none to color

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-paint#279]
If you switch the stroke from none to a color I would expect the width to change from 0 to at least 1.

The version of the shape in the editor has no width (invisible unless selected), but the one on the stage is visible.

![stroke-issue](https://user-images.githubusercontent.com/399209/35820024-7674cbba-0a72-11e8-904a-9bfd33e68768.gif)

I would also expect the stroke width to automatically switch to 0 if you select no stroke.

**Comment by carljbowman** [comment]
We should update to 1px when a color is selected after the stroke was transparent.
We should update to 0px when transparent is selected after the stroke had a color.

**Comment by fsih** [comment]
@carljbowman what happens to the color when you have a transparent outline and a stroke width of 0, and then you increase the stroke width?

**Comment by carljbowman** [comment]
We could set the stroke color to black, when the color is transparent and the stoke width is changed to anything larger than 0.

**Comment by fsih** [comment]
@benjiwheeler suggests that if the stroke width is 0 and the stroke width gets increased, it should go back to whatever color it was before it was transparent, if any.

This could cause some surprises, like if you import an SVG with stroke widths 0, and increase the stroke width, you could get unexpected colors. But it could also be surprising to have a purple stroke, and have a black stroke after changing the stroke width.

I think it wouldn't be hard to implement this way fwiw

Edit: he added the issue at https://github.com/LLK/scratch-paint/issues/697
