### ISSUE TITLE
Build new UI components

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#29]
Text-icon button in paint editor has elements of text button and icon button which are present in GUI. These should be consolidated.

**Comment by fsih** [comment]
Currently, all the files that exactly match files in GUI have this header:
/* DO NOT EDIT
@todo This file is copied from GUI and should be pulled out into a shared library.
See https://github.com/LLK/scratch-paint/issues/13 */

**Comment by mewtaylor** [comment]
@fsih should we mark this as closed now you think?

**Comment by fsih** [comment]
Yep!

**Comment by mewtaylor** [comment]
Closed in #88
