### ISSUE TITLE
Grouping and ungrouping this shape makes it lose its colors

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#301]
![groupungroupcolor](https://user-images.githubusercontent.com/2855464/36758938-ca184274-1be3-11e8-8511-830eaf3d2745.gif)

1. Draw a circle with the brush
2. Fill it in
3. Make another shape
4. Group the shapes together
5. Ungroup them

**Comment by Jacco** [comment]
Hi there,

I have been investigating the problem described here for a bit.

Replacing  this.fillItem.remove() with the following code in handleMouseUp fixes it

                var parent = this.fillItem.parent;
                this.fillItem.remove();
                parent = parent.reduce();
                parent.fillColor = this.fillColor;

Some observations that helped find the issue:
- if you fill with a different color it doesn't happen
- if you make two holes in the freedraw shape it works fine
- in the code of ungroup items are reduce()-ed

Now I am completely new to this project but would love to contribute. Let me know if you want me to convert this comment to a PR.

Regards, Jacco

**Comment by fsih** [comment]
Hi Jacco,

Thank you very much for your investigations! These look like good fixes.
I'm currently on vacation, so I won't be able to properly review them until
April, but if you could make these into pull requests, that would be great!
