### ISSUE TITLE
End caps of thick strokes sometimes not rounded

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-paint#320]
Expected: Ends of strokes are always rounded.

Actual: Sometimes the end caps are sharp edged:

![paint-arrow](https://user-images.githubusercontent.com/567844/37295536-d1d7b106-25ee-11e8-9b1e-2ee885aa61d9.gif)

I'm also seeing a warning in the console (not sure if it's related): `Skipping a merge.`

**Comment by paulkaplan** [comment]
I'm seeing something also, but not just at the end caps, it also seems to happen when i change directions

![paint-brush](https://user-images.githubusercontent.com/654102/37295750-544193dc-25ef-11e8-9540-37a5f83315ad.gif)

**Comment by kchadha** [comment]
It's happening for me on small strokes as well (size 5).
