### ISSUE TITLE
Erasing on certain costumes causes them to be filled in black

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-paint#329]
We've seen it with the knight, monet, and the spaceship.

![eraser-bug-knight](https://user-images.githubusercontent.com/567844/37736335-0b17ce08-2d27-11e8-8fa8-66a79530547e.gif)

![eraser-bug-knight-detail](https://user-images.githubusercontent.com/567844/37736501-78b7134c-2d27-11e8-9d2b-258d3e6e82c3.gif)

**Comment by fsih** [comment]
It's the holes bug, I think
https://github.com/LLK/scratch-paint/issues/120
