### ISSUE TITLE
Shape center is offset incorrectly on undo

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-paint#330]
I saw this with this project:

https://llk.github.io/scratch-gui/develop/#206831002

- do anything that will enable the undo button
- press undo
- blue rectangle is offset so its center is in the corner:

![paint-undo-bug](https://user-images.githubusercontent.com/567844/37738319-05fb27d4-2d2d-11e8-8c4e-69561a82ccde.gif)

**Comment by fsih** [comment]
@ericrosenbaum I noticed this shape also cannot be erased in the paint editor, and its fill shows up as black. How was it created? Perhaps we should generate a more paint-editor friendly backdrop for the tutorial.

**Comment by ericrosenbaum** [comment]
I created the blue rectangle in the Scratch 2.0 paint editor- pretty sure it was in the vector editor.

That project was a prototype for testing the idea of loading a starter project for the tutorial (which we are not currently planning to do).

**Comment by fsih** [comment]
For the other issues with the blue rectangle, I've filed https://github.com/LLK/scratch-paint/issues/432
