### ISSUE TITLE
Fonts for Paint Editor

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-paint#371]
### Overview
We'd like to add the ability to set a font like in 2.0. As apart of this work we'd like to swap out some fonts that will work across more platforms and support more languages.

### Font List
| 2.0 Font                   | New 3.0 Font        | New font Specimen            |
| ------------------- |------------------ | --------------------------|
| Helvetica Bold         | Noto Bold              | https://www.google.com/get/noto/                               |
| Scratch                    | _Being Designed_ | **TBD**                              |
| Donegal                   | Source Serif          | https://typekit.com/fonts/source-serif/details/source-serif-pro-regular |
| Gloria                       | Handlee                 | https://www.fontsquirrel.com/fonts/handlee |
| Marker                     | Knewave                | http://www.1001fonts.com/knewave-font.html#character-map |
| Mystery                   | Griffy                      | http://www.1001fonts.com/griffy-font.html#character-map |
| _Add Pixel font_      | Press Start P2       | https://fonts.google.com/specimen/Press+Start+2P |
| _Add Chinese_        | @thisandagain      | **TBD**                                        |
| _Add Japanese font_ | @thisandagain   | **TBD**                                        |
| _Add Korean font_  | @thisandagain      | **TBD**                                        |

### Font Menu UI
![typinating comencing - edit text mode](https://user-images.githubusercontent.com/3409578/38581643-70c1a1e8-3cdb-11e8-94a3-1bbff817495d.png)

**Comment by apple502j** [comment]
Speaking of Japanese, I suggest Sazanami Gothic
https://osdn.net/projects/efont/
Including Japanese characters (and alphabets)

Edited 2018/04/15UTC
Lite version:
apple502j/SazanamiGothicLite

Licensed under 3 clause BSD(It uses,too!)

**Comment by thisandagain** [comment]
Japanese: `font-family: "ヒラギノ角ゴ Pro W3", "Hiragino Kaku Gothic Pro", Osaka, "メイリオ", Meiryo, "ＭＳ Ｐゴシック", "MS PGothic";`
Chinese: `font-family: "Microsoft YaHei", "微软雅黑", STXihei, "华文细黑";`
Korean: `font-family: 'Malgun Gothic';`

**Comment by thisandagain** [comment]
Ideally we could use Noto (https://www.google.com/get/noto/) but the SC, TC, JP, and KR packages combined are roughly 20MB for a single weight. Because of this I think will need to fall back to system fonts.

**Comment by thisandagain** [comment]
Instead of falling back to Arial Bold I think we should use Noto Sans Bold. It is 314 KB and covers 582 languages (not including Arabic, SC, TR, JP, and KR).

**Comment by apple502j** [comment]
I don't want to use system fonts - I don't think they're always available

**Comment by apple502j** [comment]
I successfully made a size-less Sazanami Gothic.
I found that these fonts have unnecessary characters a lot!

**Comment by Kenny2github** [comment]
@carljbowman @thisandagain for a Chinese font, I would highly recommend having the font "DFKai-SB" as an option - it is the font considered most calligraphic in Chinese and would be much loved by Chinese designers.

**Comment by apple502j** [comment]
Please note - We should not rely on Microsoft fonts because Linux or tablets don't have them.
Best way is to embed open-source and libre font.

**Comment by bowstones** [comment]
@apple502j I agree with this, but the new fonts are open source anyway.

**Comment by bowstones** [comment]
Suggestion - is it possible just to link the Google Fonts open-source library by using their CSS API, thereby giving users full access to all Google Fonts?

**Comment by thisandagain** [comment]
@python-megapixel Good question! Because Scratch is used in countries where Google is blocked (like China) we cannot use Google fonts. Also, Scratch must be able to be used offline and so we need to use fonts that can be used both in the online and offline editors.

**Comment by thisandagain** [comment]
Thanks for the recommendation @Kenny2github! I'll take a look. 👍

**Comment by fsih** [comment]
![image](https://user-images.githubusercontent.com/2855464/39597793-880ce41e-4ee4-11e8-9f45-1b147e4666d0.png)

I did a comparison of the current font Helvetica, Arial, and the Noto family. Helvetica is at the bottom. and Arial's size matches extremely closely. Noto Sans Bold is a bit wider, which could cause issues with cut off text when we replace the font in projects. Noto Sans Semibold and Noto Sans Medium are closer. I think it might be good to go with Noto Sans Medium, since it's a bit narrower than Helvetica bold, which should cause fewer compatibility issues.

**Comment by thisandagain** [comment]
I leave this one up to @carljbowman. Based on this I'd be happy to go with Arial or Noto Sans Medium.

**Comment by fsih** [comment]
Here's the rest of the side by sides for completeness
![image](https://user-images.githubusercontent.com/2855464/39599018-6cd22a52-4ee8-11e8-81ba-b51b7dfdd89c.png)
