### ISSUE TITLE
A line will disappear in the paint editor if one of its corner points is dragged to flip the line.

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-paint#379]
### Expected behavior
Lines can be flipped over using one of the corner selection vertices. 

### Actual behavior
The line disappears.

### To reproduce:
Mouse over Sprite Library and click on paint.
Click the line tool and draw a horizontal line with a slight slope.
Select the selection tool
Select the line
Click and hold one of the overlapping corner points and drag towards the line or sometimes away from the line.
Notice that it will disappear as you flip the line or increase the length.

**Comment by rachel-fenichel** [comment]
![video](https://user-images.githubusercontent.com/13686399/38695799-2c23c2ce-3e42-11e8-9ef8-17c2211e97f5.gif)

**Comment by thisandagain** [comment]
Able to cause a edge-case by creating a group and performing this action in which the sprite thumbnail goes "white" and will not return.

**Comment by fsih** [comment]
Sometimes it's fine, sometimes I get the disappearing behavior, and sometimes I get this...
![circlecollapse](https://user-images.githubusercontent.com/2855464/47799098-f9c4de00-dcff-11e8-8846-d980aa92fc51.gif)

Console
Error: <path> attribute d: Expected number, "MNaN,NaNcNaN,NaN …".

**Comment by fsih** [comment]
This irrecoverably breaks the paint editor if the shape's fill or outline has a gradient. Because of that, I'm going to bump this to p2.

projects.bundle.js:47 Uncaught TypeError: Failed to execute 'createRadialGradient' on 'CanvasRenderingContext2D': The provided double value is non-finite.
    at toCanvasStyle (projects.bundle.js:47)
    at initialize._setStyles (projects.bundle.js:47)
    at initialize._draw (projects.bundle.js:47)
    at initialize.draw (projects.bundle.js:47)
    at initialize._draw (projects.bundle.js:47)
    at initialize.draw (projects.bundle.js:47)
    at initialize._draw (projects.bundle.js:47)
    at initialize.draw (projects.bundle.js:47)
    at initialize.draw (projects.bundle.js:47)
    at initialize.update (projects.bundle.js:47)
    at Array.<anonymous> (projects.bundle.js:47)
    at e (projects.bundle.js:47)

**Comment by Jacco** [comment]
@fsih This one is fixed now.

**Comment by BryceLTaylor** [comment]
This has recently been fixed.
