### ISSUE TITLE
The thickness of a drawn line cannot be changed in the paint editor.

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-paint#380]
### Expected Behavior
Lines can be made thicker or thinner using the selection tool. 

### Actual Behavior
The thickness of a line stays the same as a selection point is moved.

### Steps to Reproduce

Create a line.
Select the selection tool
Select the line
Click and hold any selection point and drag in any direction.

Thickness of the line should change as the point is dragged perpendicular to the line.

**Comment by fsih** [comment]
We were debating whether we wanted to keep this behavior in Scratch 3, in https://github.com/LLK/scratch-paint/issues/80

For instance, scaling rectangles has unintuitive behavior in Scratch 2:
![recttool](https://user-images.githubusercontent.com/2855464/38694875-c6483acc-3e58-11e8-9f9f-cd0fc2d89167.gif)

**Comment by rachel-fenichel** [comment]
Yeah, I don't have a strong position on it.  Should I close this as a dupe?

**Comment by fsih** [comment]
Sure, duping to #80
