### ISSUE TITLE
Scaled strokes become unscaled in Scratch 3.0 paint editor

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#381]
### Expected Behavior

Imported sprites should look the same in 2.0 and 3.0

### Actual Behavior

In the paint editor, imported sprites with scaled stroke widths lose their scaled thickness

### Steps to Reproduce

1. Draw a line in Scratch 2.0's vector paint editor
2. Scale it up to be much wider
3. Import the project in Scratch 3.0
![image](https://user-images.githubusercontent.com/2855464/38697490-31f82d20-3e60-11e8-96e1-8ea29e9f68cb.png)
![image](https://user-images.githubusercontent.com/2855464/38697468-191f50ee-3e60-11e8-843a-14f13e7f2ae7.png)
https://scratch.mit.edu/projects/215620314/
https://beta.scratch.mit.edu/#215620314
### Operating System and Browser

Windows 10 Chrome

**Comment by fsih** [comment]
When importing Scratch 2.0 projects, we need to convert the scaling on strokes to stroke thickness.

**Comment by fsih** [comment]
Gobo is demonstrating this problem in this project: https://llk.github.io/scratch-gui/develop/#220387166

**Comment by thisandagain** [comment]
Tracking in #618
