### ISSUE TITLE
Convert between bitmap/vector can get cut off

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#384]
### Expected Behavior

Full sprite should get converted

### Actual Behavior

The view box can get positioned strangely if you convert while zoomed in
<img width="1252" alt="screen shot 2018-04-16 at 13 42 21" src="https://user-images.githubusercontent.com/2855464/38825917-2fa67512-417c-11e8-87fd-70e7265efae2.png">

### Steps to Reproduce

1. Zoom in so the cat is cut off in the paint editor
2. Convert back and forth from vector and bitmap

### Operating System and Browser
MacOSX Chrome

**Comment by fsih** [comment]
I think the exportSVG code in convertToBitmap needs to match more closely with the handleUpdateSvg exportSVG code, saving and reseting the zoom levels. Maybe that code should be pulled out into a helper function.

**Comment by paulkaplan** [comment]
I'm going to add the "critical" label because this seems to break converting between raster/vector on all platforms.
