### ISSUE TITLE
Vector costumes with rounded corners aren't imported correctly

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-paint#394]
### Expected Behavior

- Vector costumes in 2.0 and 3.0 should render the same

#### 2.0
![image](https://user-images.githubusercontent.com/747641/39060808-5e435112-4490-11e8-8a2c-9cda3ae0e7d5.png)

#### 3.0
![image](https://user-images.githubusercontent.com/747641/39060814-64a5d200-4490-11e8-9171-d38bd54a15bb.png)

### Steps to Reproduce

https://scratch.mit.edu/projects/216633132
https://llk.github.io/scratch-gui/develop/#216633132

### Operating System and Browser

Mac OS 10.13.4  |  Version 65.0.3325.181 (Official Build) (64-bit)

/cc @fsih @cwillisf

**Comment by thisandagain** [comment]
Conversation thread with Scratcher:
![image](https://user-images.githubusercontent.com/747641/39060942-c09515ee-4490-11e8-96d7-3388746cc077.png)

**Comment by rschamp** [comment]
These costumes are also not rendered correctly on the stage:
![image](https://user-images.githubusercontent.com/1512021/44155282-e12488f8-a07a-11e8-92f3-2a32314804fe.png)

**Comment by fsih** [comment]
Here's another instance pulled from https://github.com/LLK/scratch-gui/issues/2866

The shape of the tank parts in this project
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#132801606
![screen shot 2018-08-14 at 4 50 02 pm](https://user-images.githubusercontent.com/1088291/44129840-63b3ffd2-a018-11e8-9137-921200b372cd.png)

**Comment by adroitwhiz** [comment]
This is fixed by https://github.com/LLK/scratch-svg-renderer/pull/87
