### ISSUE TITLE
Bitmap paint brush doesn't work on chromebook touch

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-paint#396]
Chrome, Samsung Chromebook

**Comment by Mr-Dave2** [comment]
Could be same issue with Ipad (Safari).  In bitmap mode the pen, used in the drawing area, just wants to scroll the web page.  However, in vector mode, it will draw a line.

![paint editor bitmap tablet problem](https://user-images.githubusercontent.com/35544966/39072245-8fc49d44-44af-11e8-8249-9d9071623fc2.gif)

**Comment by fsih** [comment]
This resurfaced in the most recent test 9/7/18

Can’t draw or use any tool more than a dot on edge with touch. Not on Android. Not on Chrome/touch @BryceLTaylor

**Comment by picklesrus** [comment]
This seems to be working now.
