### ISSUE TITLE
Converting twice causes crash in Firefox

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-paint#397]
_If it is the same as #388 you can tell me to close._

### Expected Behavior
It should never cause crash
### Actual Behavior
Crash.
DOMException: Index or size is negative or greater than the allowed amount

### Steps to Reproduce
1. Open scratch-paint
2. Draw something
3. Push "Convert to Bitmap/Vector"
4. Do it again. (In my case, twice to cause)
### Operating System and Browser
Firefox 59.0.2 Windows 7 64bit SP1 Home Premium

This GIF is taken at:
https://llk.github.io/scratch-gui/revert-1832-revert-1829-greenkeeper/scratch-paint-0.2.0-prerelease.20180420154430/

![Scratch Cat](https://i.gyazo.com/28b99f71f2db2db49ff048821ca650f8.gif)

These are at https://llk.github.io/scratch-paint/
![Crash](https://i.gyazo.com/22f3641fecb0efa1ae80ed1e902a45eb.gif)

**Comment by apple502j** [comment]
Still same as that behavior in develop branch.

**Comment by fsih** [comment]
Putting this in April so that I remember to check if it's still happening after https://github.com/LLK/scratch-paint/issues/388 is fixed

**Comment by fsih** [comment]
This should be fixed by https://github.com/LLK/scratch-paint/pull/417 , but we don't have your exact version of windows, so if you could double check and confirm it's fixed that would be really helpful :)

The fix should be on https://llk.github.io/scratch-gui/develop/ by tomorrow
