### ISSUE TITLE
Change README.md to mention bitmap editor

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-paint#398]
### Expected Behavior
It should be "Paint Editor".
### Actual Behavior
It says "Vector paint editor", but it supports bitmap now.
### Steps to Reproduce
README.md and the description
### Operating System and Browser
Windows 7 HomePremium 64bit Firefox 59.0.2
_(But no matter what the OS/browser is)_

**Comment by fsih** [comment]
Ah, good point!
