### ISSUE TITLE
In Bitmap Editor my drawings are under others

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-paint#402]
### Expected Behavior
They should be over others.
### Actual Behavior
![UNDER!](https://i.gyazo.com/ba74308185e266127c2db9ea5a6b4964.gif)
They are under them.
### Steps to Reproduce
1. Open scratch-gui/develop, which includes the bitmap editor
2. Select Cat
3. Convert to Bitmap
4. Draw!

Other ways:
1. Open scratch-paint
2. Draw some squares/circles in Vector
3. Convert to bitmap
4. Draw!
### Operating System and Browser
Windows 7 Home Premium 64bit SP1
Firefox 59.0.2

**Comment by fsih** [comment]
This is caused by the vector not turning into bitmap in Firefox, https://github.com/LLK/scratch-paint/issues/388
