### ISSUE TITLE
Converting a blank image to bitmap on Chrome makes no images appear in paint editor ever again

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-paint#409]
### Expected Behavior

If you paint a new sprite or paint a new costume for a sprite and click "convert to bitmap" you should be able to draw and update the image and other images when you select them.

### Actual Behavior

Once you convert a blank image to bitmap no images for any sprite or costume (including the one you just converted) appear in the paint editor.  You can use the tools and they change the image that appears on the stage but not the paint editor.

![convertempty](https://user-images.githubusercontent.com/1088291/39385818-ea0af3e4-4a3f-11e8-9fd3-ece0cf529f11.gif)

If you draw in the new image before converting, you don't see this behavior. 

### Steps to Reproduce

Create a new project
Open the costumes tab
Hover over the New Costume button
Click Paint new Sprite button (paintbrush)
Click Convert to Bitmap button
With the brush tool selected, draw a line on the paint editor.
Note that no line appears on the paint editor and that one does appear on the stage.
Select one of the other costumes of the cat
Note the cat doesn't appear in the paint editor but the stage now shows the cat.
Select the brush tool
Draw a line in the paint editor
Note that no line appears in the paint editor but one does appear on the cat in the stage.

### Operating System and Browser

Chrome on Mac, Chrome on Windows.

**Comment by paulkaplan** [comment]
This has been fixed, can no longer repro. Can you confirm @BryceLTaylor ?

**Comment by BryceLTaylor** [comment]
I can confirm
