### ISSUE TITLE
Text is cut off in the renderer/when converting to bitmap

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#434]
### Expected Behavior

Text should show fully

### Actual Behavior

Text can get cut off in the process of converting svg to image
![image](https://user-images.githubusercontent.com/2855464/39935343-b3101f54-5516-11e8-9c1f-37bf459c30c9.png)

### Steps to Reproduce
Open https://llk.github.io/scratch-gui/develop/#220724734

### Operating System and Browser
all

**Comment by fsih** [comment]
This is especially apparent in Marker
![image](https://user-images.githubusercontent.com/2855464/46962319-d7c92b80-d070-11e8-9443-bc87a0cf789b.png)
The g reveals that clipping of the bottom is also possible

**Comment by fsih** [comment]
Text is cut off in the Item.rasterize() method because bounds given for text are wrong
Width is calculated by paper using CanvasRenderingContext2D.measureText
https://www.w3.org/TR/2dcontext/#dom-context-2d-measuretext, which says it can be wrong:
Note: Glyphs rendered using fillText() and strokeText() can spill out of the box given by the font size (the em square size) and the width returned by measureText() (the text width). This version of the specification does not provide a way to obtain the bounding box dimensions of the text.

**Comment by fsih** [comment]
I tried changing how measure text works in Paper to render a dom element and measure that (https://stackoverflow.com/questions/118241/calculate-text-width-with-javascript)
Unfortunately, this method isn’t working. Text continues to hang out of the div bounds.
![image](https://user-images.githubusercontent.com/2855464/47226599-fd1aaa00-d38e-11e8-8e76-e9aa84274e95.png)

**Comment by benjiwheeler** [comment]
Could we add a space character at the end of each text string, and before all carriage returns, right before conversion?

I assume that would have unwanted side effects, like messing with alignment. But maybe it wouldn't?

**Comment by fsih** [comment]
Unfortunately we have some letters getting cut off from the left edge too, so we can't fix it in the text alone
![image](https://user-images.githubusercontent.com/2855464/47525622-b97edf00-d86b-11e8-8e91-f9aec8326a64.png)

**Comment by fsih** [comment]
I measured the text by converting it to an SVG and drawing that to the dom. More detail here: https://docs.google.com/document/d/1xB1bnnDhGSogeqBvZAAI9RtOymcx4cWlE7tt3IP0UYo/edit#bookmark=id.guf42bapt3fe
