### ISSUE TITLE
Text is in the wrong place when imported from 2.0 to the paint editor

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#435]
### Expected Behavior

Text should stay in the same place

### Actual Behavior
Text moves up by approximately the height of the text

### Steps to Reproduce
See https://llk.github.io/scratch-gui/develop/#220724734

### Operating System and Browser
All

**Comment by ericrosenbaum** [comment]
I'm seeing the text offset both horizontally and vertically, in this project (mac chrome and mac firefox):
https://llk.github.io/scratch-gui/develop/#209256967

2.0:
![image](https://user-images.githubusercontent.com/567844/39935773-1eada9ec-5518-11e8-8324-ce89e9bdd1e1.png)

3.0:
![image](https://user-images.githubusercontent.com/567844/39935779-25f07b30-5518-11e8-9de6-6880aaacd645.png)

**Comment by fsih** [comment]
The issue I was seeing was that the text was offset in the y direction only, and only in the paint editor

**Comment by fsih** [comment]
@ericrosenbaum The issue I fixed was only affecting Paint, not Render. I'm breaking your issue out into its own issue: https://github.com/LLK/scratch-paint/issues/472

It looks like that issue might be coming from lack of support for alignment?
