### ISSUE TITLE
Smoke Test paint issue from Friday 5/18/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-paint#454]
We found a number if issues with the font tool during the smoke test. We're not sure if they are known or already have issues filed.  This issue is to make sure everything gets triaged.

@fsih I've added who found it to each issue if you need more information.  At the bottom I've added who was using which operating system/browser

* [x] Double clicking text with the Select tool does not allow you to edit the text. It should transition to the Text tool and set the state of the text element to edit. @carljbowman 
* [x] While text is selected (outside of the text tool), should I be able to change the font? @rschamp 
* [ ] Scaling a block of serif type causes the editor to get into a state where the changes made with the font tool in the costume editor are not reflected on the stage (switching to sans-serif?) @thisandagain 
* [x] While typing into the paint editor, the stage updates one letter behind what’s visible in paint. @rschamp 
* [x] Highlighting Text completely hides the text in the selection: @carljbowman 
![image11](https://user-images.githubusercontent.com/1088291/40249049-d0097ae0-5a9f-11e8-9576-26a8213215aa.png)
* [x] Direct selection of text is confusingly different from regular selection @rschamp 
* [x] When text is selected with the Select tool and you click to the Text tool, the selected text element loses selection. @carljbowman 
* [ ] Somehow I got into a state where I could select some of the paths of the controls. I created a couple pieces of text, changed their fonts, distorted them, and selected them with different selection modes. I think I also used the paint bucket. @rschamp 
* [x] Somehow got into a state where the scale / proportions of the text I’m editing in the costume editor is not the same as what is being rendered to the stage. @thisandagain 
* [x] Adding a very thick outline to text can be rendered differently between the costume editor and the stage. @thisandagain 
* [x] Really hard to drag text with an outline and no fill @BryceLTaylor
* [x] The selection box around text with the pixel font set is incorrect. For the word “font” for example, the tops of the “f” and “t” extend above the box, and the bottom of the box is too low. @ericrosenbaum 
* [x] Multi-line selection of text is really wonky. Create a text box, type and add new lines, and then try to select all the text. @carljbowman 
* [x] The dotted UI bounding box that appears while editing text becomes out of sync with the size of the text. @carljbowman 
![image13](https://user-images.githubusercontent.com/1088291/40249274-73e48376-5aa0-11e8-82fa-ef2f0861c4cb.png)
* [x] Unhandled error (korean font with outline and resized) partial errors from console (chromebook): https://pastebin.com/mJQni1hu @chrisgarrity 
* [x] Font is rendering in the wrong place, size, and font on the stage. @rschamp 
![image8](https://user-images.githubusercontent.com/1088291/40249401-e299f742-5aa0-11e8-9cb1-9abdb4608142.png)

Device | Browser | Name
-- | -- | --
Windows* | Chrome |  
Mac | Chrome | Andrew, KO
iPad | Safari | Karishma
Chromebook | Chrome | Eric
Windows* | Firefox |  
Android Tablet | Chrome |  
Windows* | Edge | Bryce
Mac | Safari | Ray
Mac | Firefox | Carl

**Comment by fsih** [comment]
While text is selected (outside of the text tool), should I be able to change the font? @rschamp

I think we talked about this with @carljbowman and we decided no, the text mode tools only appear when the text tool selected, but correct me if that's wrong Carl

**Comment by fsih** [comment]
Filed https://github.com/LLK/scratch-paint/issues/461 for select tool features

**Comment by fsih** [comment]
While typing into the paint editor, the stage updates one letter behind what’s visible in paint. @rschamp

Filed https://github.com/LLK/scratch-paint/issues/462

**Comment by fsih** [comment]
Highlighting Text completely hides the text in the selection: @carljbowman

Filed https://github.com/LLK/scratch-paint/issues/463

**Comment by fsih** [comment]
Direct selection of text is confusingly different from regular selection @rschamp

Filed https://github.com/LLK/scratch-paint/issues/464

**Comment by fsih** [comment]
Somehow I got into a state where I could select some of the paths of the controls. I created a couple pieces of text, changed their fonts, distorted them, and selected them with different selection modes. I think I also used the paint bucket. @rschamp

@rschamp Do you mind filing this issue? I didn't understand what you meant

**Comment by fsih** [comment]
Somehow got into a state where the scale / proportions of the text I’m editing in the costume editor is not the same as what is being rendered to the stage. @thisandagain

Font is rendering in the wrong place, size, and font on the stage. @rschamp

I'm guessing this was https://github.com/LLK/scratch-paint/issues/436, which should be fixed now

**Comment by fsih** [comment]
Adding a very thick outline to text can be rendered differently between the costume editor and the stage. @thisandagain

Filed https://github.com/LLK/scratch-paint/issues/465

**Comment by fsih** [comment]
The selection box around text with the pixel font set is incorrect. For the word “font” for example, the tops of the “f” and “t” extend above the box, and the bottom of the box is too low. @ericrosenbaum

The dotted UI bounding box that appears while editing text becomes out of sync with the size of the text. @carljbowman

Filed https://github.com/LLK/scratch-paint/issues/467

**Comment by BryceLTaylor** [comment]
* [X] Really hard to drag text with an outline and no fill @BryceLTaylor  https://github.com/LLK/scratch-paint/issues/466

**Comment by fsih** [comment]
Multi-line selection of text is really wonky. Create a text box, type and add new lines, and then try to select all the text. @carljbowman

Filed https://github.com/LLK/scratch-paint/issues/468

**Comment by fsih** [comment]
Unhandled error (korean font with outline and resized) partial errors from console (chromebook): https://pastebin.com/mJQni1hu @chrisgarrity

Filed https://github.com/LLK/scratch-paint/issues/469

**Comment by fsih** [comment]
Scaling a block of serif type causes the editor to get into a state where the changes made with the font tool in the costume editor are not reflected on the stage (switching to sans-serif?) @thisandagain

@thisandagain I couldn't repro this, do you mind filing if you find a repro?
