### ISSUE TITLE
"Center" button when using rotation point tool

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-paint#456]
Building on #32, it would be handy to have a "center" button when the rotation point tool is active. This would make it so the rotation point is put in the middle of the costume.

Example usage - changing this...

![A 5-point cartoon star; the rotation point crosshair is slightly offset from the middle](https://user-images.githubusercontent.com/9948030/40309898-8a25c2d8-5ce1-11e8-8f9c-ed2735b68fb0.png) ![A red ball, also with an offset rotation point](https://user-images.githubusercontent.com/9948030/40310001-d4c816d8-5ce1-11e8-9a84-2a1b4b5181dc.png)

...to this:

![The same star, but with the rotation point in the center](https://user-images.githubusercontent.com/9948030/40309924-9a10e9e8-5ce1-11e8-87b6-4d68fa586339.png) ![The same ball, but with the rotation point in the center](https://user-images.githubusercontent.com/9948030/40310011-dce382d0-5ce1-11e8-94d7-96c84bea022b.png)

(The costumes in the first set of images would rotate sort of wobbly; the second set would rotate around their actual middle, without any wobble. Compare rotating them in the 2.0 editor!)

**Comment by kaaaaathy** [comment]
@towerofnix @GarlandKey @kadhonn @apple502j, @adroitwhiz, @epicfaace, @DeleteThisAcount

Thanks so much for all your thoughts on this! it's awesome to see how much people care about this feature. We'd like to get some more info from you all about this particular center tool; we want to think about things as holistically as we can before we add a new tool in the toolbar.

Other than the fact that centering is generally helpful... We would love to better understand what use cases this might help with most. e.g. is it hard to get things consistently centered across animation frames? How often do you think this would be used? There are multiple ways we might go about solving this, depending on what the use case(s) are. 

Thanks :)

**Comment by epicfaace** [comment]
I think @towerofnix put it well -- having the center button will make sure that the "rotation point is put in the middle of the costume" -- otherwise, it requires manual dragging and estimating to put the center in the right place. It was also there in earlier versions of Scratch.

**Comment by kadhonn** [comment]
Yes, in my case (I speak with two years of experience working with children in the setting of a CoderDojo) it's also about the rotation point.
When you have a sprite which gradually turns, a bit of wobble may be acceptable, but if the sprite turns in steps of 90 or 180 degrees, if the image is not centered, it will jump around.
Without any help it's really hard and a lot of guesswork to make that work perfectly.

In my experience in ~95% of all cases I just want to center my image as good as possible, that's why I went for the "center button" instead of the old rotation tool. I also included two commits which made the current rotation point aka center visible layered on top of your image when you drag it around, in case you don't want to center it but need a custom rotation point.

**Comment by DeleteThisAcount** [comment]
@towerofnix got it exactly. What I use it for most is aligning the center of a sprite to rotate. Without it it's just trial and error which takes time and really can slow something that could have been a 2 step process of choosing the tool and moving it to the center.

Otherwise rotation looks off or is just plain wrong.

**Comment by towerofnix** [comment]
>There are multiple ways we might go about solving this, depending on what the use case(s) are.

@kathymakes Since all the posts here are generally in agreement that their common use case is for making the sprite rotate around its center, if you don't mind for discussion, could you share some of your ideas for solving this differently from using a "center" button that shows up while the "set rotation center" mode is selected (i.e. like Scratch 2.0)?

**Comment by DeleteThisAcount** [comment]
i have an idea that may make this idea redundant, what about a center option that takes moves whatever is drawn to the exact center of the canvas? this could make it even easier for new scratchers. @towerofnix

**Comment by adroitwhiz** [comment]
Going to throw another potential solution onto the pile:

1. Display the crosshair at the center of the canvas above all drawings when something is being dragged. This fills in for the behavior of 2.0's "center" tool, which allows you to place a crosshair above where you want the center to be and then centers it there, and is a somewhat imprecise way of centering.

2. Add a "center" tool, which centers all canvas contents based on the center of the selected object(s). What I mean by this is that the selected object(s) will be moved so their center is the canvas' center, and non-selected objects will be moved along with them. If no objects are selected, the "center" will be that of the bounding box of every object. This allows users to specify which *object* is the center of the drawing, while 1. allows users to specify which *point* is the center.

**Comment by towerofnix** [comment]
Oh, I'd actually forgotten, in discussing current solutions, that [there is no rotation point tool in 3.0 (yet)](https://github.com/LLK/scratch-paint/issues/32). IMO that tool wasn't very intuitive, so making it more-so and solving this at the same time would be very useful. @adroitwhiz I like your solutions a lot!

<details><summary>(For comparison with solutions, here's my current workaround when trying to center elements accurately.)</summary>

1. Create a "crosshair" costume, which has lines drawn over the x/y axes, centered at (0, 0) on the costume.
2. Copy it and paste it into the costume I want to center. (Scratch 3.0 always pastes costume parts at the same location they were copied from.)
3. Select everything in the to-be-centered costume, except the crosshair, so I can see the bounding box for the costume.
4. Move the selected parts so that the midpoints on the bounding box's edges line up with the pasted-in crosshair.
5. Remove the crosshair lines from the costume.

Note I don't just draw a dot, or some other small shape above (0, 0); I draw lines along the axes. This is so that I don't have to leave so much of the center-accuracy up to eyeballing. @adroitwhiz, if your first solution only shows the crosshair icon above everything else, the same problem would come up: it'd involve a lot of eyeballing. But displaying lines over the axes like I do, whenever anything is dragged in the costume editor, could be very distracting.

Also, your second solution can be done in 3.0 with an additional step: place axis-lines over the center of the individual object you want to center, and then drag everything (except the (0, 0) crosshair lines) so that the new axis-lines overlap with the (0, 0) ones. Then delete the excess lines. This also works for centering on any particular point on the costume.</details>

But obviously, these workarounds are what we're trying to avoid. I prefer your second solution, because the first one has a more simple workaround - just paste axis-lines over (0, 0) from a separate costume, where you know they are accurately placed at (0, 0). The second solution makes it much more easy to center around any particular part of the costume, which I think is 1) a more interesting tool to play with for exploring users, and 2) a simplification of a more complicated process (aligning two sets of axis-lines). Also, it's 100% accurate, unlike any workaround; it's a tool specifically designed to perfectly center the costume around whatever object you choose.

Unrelatedly, I'd considered suggesting 'guide lines' or 'snap points' like many design-editor programs have? So, instead of automatically showing the crosshair or a set of axis-lines whenever you're dragging, it would only show those - and snap the costume to the accurate center - if you were already dragging the sprite close to the center. But this might be confusing to inexperienced users, so :woman_shrugging: I don't think it's as useful or playful as a button which centers the selected object and brings the rest of the costume with it.

**Comment by kadhonn** [comment]
@adroitwhiz that is pretty much what i implemented in this pull request: #908 (without the select what to center, it always centers the whole object)

**Comment by adroitwhiz** [comment]
@towerofnix Does the new crosshair tool provide this functionality?

**Comment by towerofnix** [comment]
@adroitwhiz I'd say so! Thanks!
