### ISSUE TITLE
Text can become clipped on the Stage when scaling a text element

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-paint#475]
### Expected Behavior
Text should not become clipped.

### Actual Behavior
It's important to use a text that extends beyond the bounding box. 
<img width="131" alt="screen shot 2018-05-24 at 11 49 30 am" src="https://user-images.githubusercontent.com/3409578/40496779-8eab546c-5f48-11e8-8ce9-dfb00d3ffe3a.png">

![text clipping](https://user-images.githubusercontent.com/3409578/40496699-64e2b72e-5f48-11e8-8cba-17cc7eda2b15.gif)

### Steps to Reproduce
1. Use the text tool to create some text
2. Rescale the text box
3. Check the stage for clipping

### Operating System and Browser

OS: macOS 10.13.4
Browser: Chrome Version 66.0.3359.18

**Comment by thisandagain** [comment]
Tracking in #434
