### ISSUE TITLE
Outlined text should look the same on the stage

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-paint#480]
### Expected Behavior
Text with outlines should look the same on the stage and in the paint-editor.

### Actual Behavior

<img width="981" alt="screen shot 2018-05-25 at 12 49 13 pm" src="https://user-images.githubusercontent.com/399209/40665718-009d8f22-632c-11e8-807f-c652f492b87e.png">

### Steps to Reproduce
* Enter some text with the text-tool
* resize with the selection tool
* select a color
* select a color for the stroke, and increase the size of the stroke.

### Operating System and Browser

Mac OS 10.13.4, Firefox

**Comment by thisandagain** [comment]
Tracking in #465
