### ISSUE TITLE
Feature request: Select all, deselect, and delete in select mode

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#498]
1. If sprites are going to be deselected by default, it may be nice to have a select all button. It can be impossible to drag select everything, especially when working on a background. It would also help with retrieving parts that are "lost" off the edges of the paint editor.
2. For the same reason it can be difficult to deselect everything. For instance, draw a rectangle that fills the paint editor. (Esc might be a good keyboard shortcut to add for this)
3. Delete is currently only available as a keyboard shortcut, which may not be obvious and may not work on tablets.

These actions could be available in the buttons at the top, or a context menu

/cc @carljbowman

**Comment by chexbox** [comment]
keyboard shortcuts?
