### ISSUE TITLE
Uncaught TypeError: this._modeMap[this.mode].onMouseUp is not a function

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#521]
### Expected Behavior
Select tool doesn't draw infinite selection boxes
### Actual Behavior
![image](https://user-images.githubusercontent.com/2855464/41730699-6eeece34-754a-11e8-9ec3-0abc203ca368.png)

### Steps to Reproduce
I'm not sure how this happened ):
I was using the reshape tool, and then clicked off of the thing I was reshaping.

### Operating System and Browser
Windows 10 Chrome

**Comment by adroitwhiz** [comment]
Is this a duplicate of https://github.com/LLK/scratch-paint/issues/546?

**Comment by fsih** [comment]
That bug was closed by this commit https://github.com/LLK/scratch-paint/commit/90bc640dbb939d60c311fc0da409e46ef6730546

You're right, looks like it was the same bug!
