### ISSUE TITLE
Color selector is very difficult to use for colorblind users

### ISSUE THREAD

**Issue by bowstones** [LLK/scratch-paint#526]
I am colourblind, meaning that I cannot identify or distinguish between certain similar colours. The new Scratch colour selector therefore makes it incredibly difficult for me to select the colour I want. For example, let's say I wanted to make something bright orange. I could move the sliders like anyone else, but I would have no way of knowing whether I had actually made it bright orange, or whether it was red, or yellow, or pink.

There are many solutions to this. I have listed them here in the order of what would make it easier for me:

1. A field a the bottom which accepts HTML colour values. I could type in "orange" for example.
2. A set of predefined colors with labels such as "sky blue", "bright orange" etc.
3. The ability to enter specific values into the C/S/V selector (I could google the right values)

**Comment by Kenny2github** [comment]
You're color-blind too? What kind?

It's hard to allow HTML color values while guarding against security issues at the same time, though. Predefined colors are better. Specific values would also be good.

**Comment by thisandagain** [comment]
We will be adding a color "swatch" selector in the future.

**Comment by bowstones** [comment]
@thisandagain That won't help unless the colours have tooltips (i.e. it should have a box which shows up which says "sky blue" if I hover over the sky blue option)

**Comment by fsih** [comment]
What features of color pickers help you guys most in existing software? Do you rely on swatches to be in a certain order? Having some good examples to play with could help us.

**Comment by Kenny2github** [comment]
@fsih I tend to rely on an HTML-to-RGB converter and input specific RGB values, or stick to certain RGB values which I know to be definitely a certain color:
* #f00 for red
* #0f0 for green
* #00f for blue
* #ff0 for yellow
* #f0f for magenta
* #0ff for cyan
* #fff for white
* #000 for black
* #xxx (where x is the same digit) for grays
But other colors I am usually uncertain about; therefore tooltips on a predefined color palette help a lot as well.
