### ISSUE TITLE
Tools with transparent/no fill in bitmap draw black

### ISSUE THREAD

**Issue by hyperobject** [LLK/scratch-paint#535]
### Expected Behavior
In the bitmap editor, painting with color set to transparent in should behave the same as the erase tool, and drawing shapes with fill transparent should not draw anything (or erase an area that matches the shape drawn).

<img src="https://user-images.githubusercontent.com/3019167/41975980-d65878a6-79e9-11e8-9ec2-ac4e143d0eda.gif" width="300px" />

### Actual Behavior
Using the paint tool or drawing ovals and rectangles draws with black instead of transparent/erasing areas of a drawing.
<img src="https://user-images.githubusercontent.com/3019167/41976064-0f2dc06e-79ea-11e8-8dfe-35cf4ef15507.gif" width="300px" />

### Steps to Reproduce
In the Scratch 3.0 editor, open a bitmap drawing and set fill to transparent. Draw with the paint, oval, or rectangle tools.

### Operating System and Browser

Chrome OS 66, macOS 10.13.5 Firefox Nightly 63

**Comment by fsih** [comment]
Plans for transparent fill
- The brush should become an eraser
- Line, rect, and oval should have transparent color missing from fill menu

**Comment by msjessicagamble28-dev** [comment]
ftcytfy
