### ISSUE TITLE
Bitmap loads in the wrong place

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#557]
### Expected Behavior
Bitmap loads in the same place in 2.0 and 3.0

### Actual Behavior
Bitmap moves in this project
https://llk.github.io/scratch-gui/develop/#144885018

### Steps to Reproduce
Open https://llk.github.io/scratch-gui/develop/#144885018
Go to costumes tab
Make sure Reference sprite is selected
The bitmap should be centered, but it's offset down and to the right

### Operating System and Browser
Mac Chrome

**Comment by thisandagain** [comment]
Looks like this is now working properly.

**Comment by BryceLTaylor** [comment]
In this project the "cover" sprite does not appear correctly positioned in the paint editor: 
[3.0](https://llk.github.io/scratch-gui/develop/#247578672)
![screen shot 2018-09-26 at 10 22 52 am](https://user-images.githubusercontent.com/1088291/46086506-3a1bc400-c176-11e8-9bd4-bfe83cb1cf25.png)

[2.0](https://scratch.mit.edu/projects/247578672/#editor)
![screen shot 2018-09-26 at 10 23 01 am](https://user-images.githubusercontent.com/1088291/46086507-3c7e1e00-c176-11e8-816c-29fb1976f31e.png)

The elements in the costume were created as bitmaps in 2.0 (photos in this case) and then it was converted to vector so they could be positioned.   In 3.0, when it comes in as vector the images are positioned incorrectly.

You can reproduce this easily:
Create a new 2.0 project
Add a new sprite (should be in bitmap)
Draw a shape (circle, squiggle, anything) but keep it relatively small and near the center of the paint editor
Convert the sprite to vector
reposition the shape you draw closer to an edge of the editor
Save the project
Open the project in 3.0
Select your sprite and open the paint editor
Note: in 3.0 the image is drawn in the wrong place.  It will have moved farther from the center than you originally had it.  Sometimes they end up off the paint editor entirely.

**Comment by BryceLTaylor** [comment]
These sprites also seem to be causing the project to slow down greatly when the paint editor is open to one of them.  This seems to be related to this issue: https://github.com/LLK/scratch-gui/issues/3172 and it causes [Geometry Dash](https://llk.github.io/scratch-gui/develop/#105500895)  to slow way down.

**Comment by fsih** [comment]
https://github.com/LLK/scratch-paint/issues/632 seems to be another instance of this

**Comment by fsih** [comment]
I'm adding the words Space Giraffe in the comments because I never remember how to search for this issue but I can remember Space Giraffe.

Space Giraffe Space Giraffe Space Giraffe Space Giraffe Space Giraffe Space Giraffe

**Comment by fsih** [comment]
Incoming SVG
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="247" height="265" viewBox="-1 -1 247 265">
  <!-- Exported by Scratch - http://scratch.mit.edu/ -->
  <image id="ID0.9583349949680269" width="490" height="526" xlink:href="..." transform="matrix(0.5, 0, 0, 0.5, 0, 0)"/>
</svg>
```
Outgoing SVG
```
<svg height="263" version="1.1" width="245" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
	<g transform="translate(-118,-50)">
		<g data-paper-data="{&quot;isPaintingLayer&quot;:true}" fill="#000000" fill-rule="nonzero" font-family="none" font-size="none" font-weight="none" stroke="none" stroke-dasharray="" stroke-dashoffset="0" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-width="none" style="mix-blend-mode: normal" text-anchor="none">
			<image height="526" id="ID0.9583349949680269" stroke="none" stroke-width="1" transform="scale(0.5,0.5)" width="490" x="236" y="100" xlink:href="..."/>
		</g>
	</g>
</svg>
```

The added painting layer group is always added by Paper.  The weird things are the added transform group and the X and Y added to the image
```
<g transform="translate(-118,-50)">
x="236" y="100"
```
Basically moving it over just to translate it back, with an offset that seems to be coming out of nowhere.

**Comment by fsih** [comment]
Reopening since it was rolled back
