### ISSUE TITLE
Latest scratch-svg-renderer is not available

### ISSUE THREAD

**Issue by ValentinZhao** [LLK/scratch-paint#561]
### Expected Behavior

The painter should install all its dependencies properly after I run `npm install` in my terminal.

### Actual Behavior

Error log 

`No matching version found for scratch-svg-renderer@0.2.0-prerelease.20180712223402`

emerges and stops my installing.

### Steps to Reproduce

run `npm install` on latest `develop` branch

### Operating System and Browser

Mac OS 10.11

**Comment by ValentinZhao** [comment]
Okay for now, it turns out `scratch-render-fonts@1.0.0-prerelease.20180605131737` has not published to npm yet. I would better to wait you guys finishing publishing.

**Comment by thisandagain** [comment]
This should now be resolved.

**Comment by ValentinZhao** [comment]
Nope, there is no published version `0.2.0-prerelease.20180712223402`. Am I supposed to install on `develop` branch?

You shall check published versions via `npm view scratch-svg-renderer` and looking for `versions` field.

**Comment by thisandagain** [comment]
@ValentinZhao I recommend you purge your NPM cache (`npm cache clean --force`). The current status of the `scratch-svg-renderer` package:

```
scratch-svg-renderer@0.2.0-prerelease.20180712223402 | BSD-3-Clause | deps: 5 | versions: 30
SVG renderer for Scratch
https://github.com/LLK/scratch-svg-renderer#readme

dist
.tarball https://registry.npmjs.org/scratch-svg-renderer/-/scratch-svg-renderer-0.2.0-prerelease.20180712223402.tgz
.shasum: 147b2ce41e32e70efc48bce9e6e590090f1f909b
.unpackedSize: 1.6 MB

dependencies:
base64-js: 1.2.1
base64-loader: 1.0.0
jimp: 0.2.27
minilog: 3.1.0
scratch-render-fonts: 1.0.0-prerelease.20180605131737

maintainers:
- scratch <scratchr-sysadmin@media.mit.edu>

dist-tags:
latest: 0.2.0-prerelease.20180712223402
```

**Comment by ValentinZhao** [comment]
Never mind, I installed a previous version of this repo and got it started. Thanks for your time. @thisandagain
