### ISSUE TITLE
Localize tool tooltips

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-paint#562]
### Expected Behavior

_Please describe what should happen_
The tooltips (title) for tools like 'circle', 'text', 'rectangle' should be extracted for localization.

### Actual Behavior

_Describe what actually happens_
Passing the FormatMessage descriptor as a prop is not recognized by the tools as a localization string definition, so it is not extracted. Any strings created this way are not available to translators for translation.
```
<ToolSelectComponent
        imgDescriptor={{
            defaultMessage: 'Circle',
            description: 'Label for the oval-drawing tool',
            id: 'paint.ovalMode.oval'
        }}
        imgSrc={ovalIcon}
        isSelected={props.isSelected}
        onMouseDown={props.onMouseDown}
    />
```
### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
Switch to any language other than English (e.g., Italian, French, Spanish) the tooltips are not translated.

If you log on to transifex and search for 'circle' in the Scratch Editor, it is not found.

**Comment by chrisgarrity** [comment]
If anyone wants to implement this, you would just need to find all the places where imgDescriptor is an object and replace it with the descriptor generated by `defineMessages`.
1. Import defineMessages from react-intl. `import {defineMessages} from 'react-intl';`
2. Define descriptors with defineMessages. E.g.:
```
const messages = defineMessages({
    circle: {
        defaultMessage: 'Circle',
            description: 'Label for the oval-drawing tool',
            id: 'paint.ovalMode.oval'
});
```
3. Replace `imgDescriptor` prop.
```
 <ToolSelectComponent
        imgDescriptor={messages.circle}
        imgSrc={ovalIcon}
        isSelected={props.isSelected}
        onMouseDown={props.onMouseDown}
    />
```

**Comment by apple502j** [comment]
oops, needs to be closed...
