### ISSUE TITLE
Swapping colors in the gradient tool breaks on compound paths

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-paint#567]
### Expected Behavior

Swapping colors in the gradient picker should still continue to work regardless of shape.

### Actual Behavior

![gradients](https://user-images.githubusercontent.com/3409578/43007457-643d9cd6-8c06-11e8-97f8-04ccd3632311.gif)

### Steps to Reproduce

1. Draw a shape with gradient 
2. Erase a hole into the shape to create a compound path
3. Swap colors in the gradient
4. Erase another hole into the the shape
5. Try swapping colors

### Operating System and Browser

Browser: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
OS: macOS 10.13.6

**Comment by fsih** [comment]
It works with odd numbers of holes but not even o_O
I don't see anything obvious that could be causing this. Paper uses flags to determine if anything has changed. It may be somewhere in the flag logic.
