### ISSUE TITLE
Make paint work for RTL languages

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-paint#574]
### Expected Behavior

Everything should be laid out correctly when using an RTL language such as Hebrew.
- [ ] buttons should have the rounded corners on the 'outside':
![screen shot 2018-08-06 at 4 58 44 pm](https://user-images.githubusercontent.com/399209/43740737-247c57d0-999a-11e8-9ee0-ae6b4d41ea8e.png)
![screen shot 2018-08-06 at 5 00 16 pm](https://user-images.githubusercontent.com/399209/43740761-3864f162-999a-11e8-9f76-8be7115be105.png)
- [ ] labeled inputs should have margin mirrored
- [ ] undo/redo arrows will need to be mirrored
- [ ] button icons need margin reversed:
![screen shot 2018-08-06 at 5 02 22 pm](https://user-images.githubusercontent.com/399209/43740875-8b397e12-999a-11e8-9e31-4793b1edd02b.png)
- ~~[ ] editing text with the text tool should put the cursor in the correct place~~ (split out to #615)

Splitting out from https://github.com/LLK/scratch-gui/issues/1579

### Actual Behavior

_Describe what actually happens_
Layouts specific to LTR look broken on RTL - e.g. margin on the wrong side.

**Comment by paulkaplan** [comment]
Also the text tool puts the cursor in the wrong place
