### ISSUE TITLE
On Android, eyedropper button doesn’t do anything

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#579]
On Android, eyedropper button doesn’t do anything @ericrosenbaum

**Comment by picklesrus** [comment]
It currently does stuff on my phone. But it isn't obvious... if you hold your finger down and move it around it does, after a bunch of attempted taps in various places to drop focus, pick a a color.  But it could use some work on touch.

**Comment by picklesrus** [comment]
Consolidating into https://github.com/LLK/scratch-gui/issues/1350
