### ISSUE TITLE
Bitmap Shapes disappear if you don't click off of them and then switch costumes

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#595]
In bitmap, if you make a circle or square and don't click off of it, it doesn't show up on stage and it disappears if you switch costumes and back

**Comment by ericrosenbaum** [comment]
@fsih I'd recommend changing the title of this one to reflect the severity (something more like "shapes are unexpectedly deleted").

![bitmap-loses-shape](https://user-images.githubusercontent.com/567844/44343865-1a99c900-a45d-11e8-853a-2f7dcd82ff45.gif)

**Comment by fsih** [comment]
Ohhh this is that issue you had in the smoke test!

**Comment by fsih** [comment]
Oh no, I found a crash
1. Switch to bitmap
2. Switch to oval tool
3. Toggle to outline
4. Draw an oval
5. Toggle to filled
6. click off
crash

**Comment by fsih** [comment]
Aha, I think it was those Widhs
