### ISSUE TITLE
Paint editor should scale to fill available space

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-paint#601]
### Expected Behavior

The paint editor should fill up as much space as is available in the Costumes/Backdrops pane.

### Actual Behavior

It is fixed to being 480 pixels wide and 380 pixels tall unless you zoom in your browser.

### Steps to Reproduce

Open the paint editor (click the Costumes tab).

---

This is a very common feature request in the 3.0 beta forums, usually along the lines of "the paint editor is way too small".

(Sorry if this is a duplicate! I couldn't find one, but I somewhat remember seeing one before.)

---
Moved from LLK/scratch-gui#2754
/cc @towerofnix

**Comment by fsih** [comment]
Part 2 of https://github.com/LLK/scratch-paint/issues/166
Discussion doc: https://docs.google.com/document/d/1E1y6nUbBrpqK6XdJyBy2XlSGf0oaxrprY-YXW16HdNk/edit
Related: https://github.com/LLK/scratch-paint/issues/578 (svgs should be downsized to fit paint editor)
