### ISSUE TITLE
When nothing is selected have Copy and Delete act on all artwork

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-paint#605]
### Overview
Currently when nothing is selected, clicking Flip Horizontal or Flip Vertical will cause the action to effect all the artwork within a Costume or Backdrop. 

Both Copy and Delete actions feel like good candidates for a similar UX. 
- Delete would act like Scratch 2.0's Clear feature.
- Modifying Copy would mean someone would not have to drag-select everything to Copy / Paste it — as we have seen drag selecting can be challenging for new comers.

### Delete Flows (similar to Scratch 2.0's Clear)
**Delete via UI**
1. Have none of the artwork selected 
2. Delete UI would appear enabled
3. Clicking Delete would delete all artwork within a Costume or Backdrop

**Delete Key**
Deleting everything if you hit the delete key might feel jarring, so let's not optimizing the keyboard input to clear everything.

### Copy Flows
**Copy via UI**
1. Have none of the artwork selected
2. Copy UI would appear enabled
3. Clicking Copy would copy all of the artwork within a Costume or Backdrop

**Copy via Hotkeys**
1. Have none of the artwork selected
2. Using the Copy hotkeys would copy all of the artwork within a Costume or Backdrop

/cc @ntlrsk

**Comment by carljbowman** [comment]
@fsih - Updated the original comment to include the UX that we discussed for hotkeys. WOO! PAINT EDITOR HOTKEYS!

**Comment by fsih** [comment]
Filed https://github.com/LLK/scratch-paint/issues/653
