### ISSUE TITLE
See exact middle of object when selected

### ISSUE THREAD

**Issue by DeleteThisAcount** [LLK/scratch-paint#607]
### Expected Behavior

Should show a circle in the exact center of selected object:

![](https://i.gyazo.com/6972b4b4ff857e8c13ef2973ead6d0d3.png)

### Actual Behavior

Does not:

![](https://i.gyazo.com/6c13c2deac447ae02299450cfdd4c203.png)

### Steps to Reproduce
Open paint editor
Select object
Notice missing circle

**Comment by chexbox** [comment]
Related to #528?

**Comment by DeleteThisAcount** [comment]
this is still relevant, and yes related to #528, not sure how active this repo is though

**Comment by DeleteThisAcount** [comment]
This was added, so I'm going to close this.
