### ISSUE TITLE
On iPad mini, tapping and holding a scroll bar causes a gray overlay to appear over the left half of the screen

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#613]
On iPad mini, tapping and holding a scroll bar causes a gray overlay to appear over the left half of the screen. Trying to drag them causes the entire page to scroll slightly

From @rschamp smoke test 8/17/18
### Operating System and Browser
iPad mini

**Comment by picklesrus** [comment]
closing as duplicate of https://github.com/LLK/scratch-paint/issues/703
