### ISSUE TITLE
Handle RTL languages in the text tool

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-paint#615]
Splitting out from #574 

- When typing in a RTL language, the textarea should grow to the left (it currently grows to the right)
- When selecting text in an existing RTL textarea the cursor should appear where the mouse was clicked
- If all the text is selected (e.g. by double clicking), the highlight should appear over the text (currently appears offset to the right)
- it should be possible to select a substring of a RTL textarea

@fsih I think we need to pair on this one.

**Comment by fsih** [comment]
@chrisgarrity happy to pair whenever :+1:
