### ISSUE TITLE
Shape loses color if you erase around a hole

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#621]
### Expected Behavior
Erasing does not change colors

### Actual Behavior
Erased shape turns white

### Steps to Reproduce
![erasehole](https://user-images.githubusercontent.com/2855464/44554831-864f9080-a700-11e8-853a-bd49a7a6b295.gif)
1. Erase a hole in a shape
2. Erase over the hole with a bigger eraser

### Operating System and Browser
Mac OSX Chrome

**Comment by adroitwhiz** [comment]
Also mentioned in [this Bugs and Glitches post](https://scratch.mit.edu/discuss/topic/381207/).
