### ISSUE TITLE
In 2.0 into vector converted graphics change position in paint editor

### ISSUE THREAD

**Issue by LiFaytheGoblin** [LLK/scratch-paint#632]
### Expected Behavior
Any graphic in 2.0 and 3.0 should have the same position in the paint editor. There seems to be a problem with bitmap graphics converted into vector: They change their position in the paint editor, but thumbnails and stage look good.

<img width="1679" alt="screen shot 2018-08-29 at 2 43 20 pm" src="https://user-images.githubusercontent.com/5471273/44808316-e7acaf00-ab99-11e8-9519-b29f7012abe0.png">

### Steps to Reproduce
Go to the 2.0 editor. Create a bitmap costume. Convert to vector. Save. Open in 3.0. 
It doesn't matter whether you move the converted object afterwards, group it, or if you drag&dropped a bitmap costume into a vector costume.

I used 242547591 for testing. Discovered in 114563396.

### Operating System and Browser
MacOS, Chrome

**Comment by fsih** [comment]
Ooh, good find
