### ISSUE TITLE
Fill preview doesn't update when scrolling the paint editor

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#638]
Paint Editor: Had fill tool selected. Zoomed in, wanted to scroll, accidentally used fill tool on vector object. Can’t revert, thumbnail still shows the old color of the object. Then I acccidentally clicked somewhere and suddenly the object is back in it’s old color again. @LiFaytheGoblin

I think what you're seeing when you thought you accidentally used the fill tool is the fill preview, which doesn't change what the sprite looks like on stage. If you scroll while something is fill previewed, it doesn't update the preview.
![fillscroll](https://user-images.githubusercontent.com/2855464/44879173-e9987000-ac76-11e8-876d-396821e04afb.gif)

**Comment by LiFaytheGoblin** [comment]
Hm, that seems plausible!

**Comment by Jacco** [comment]
Tested this one with my fix on #401, this is fixed too :-)

![panfill](https://user-images.githubusercontent.com/1318341/52393185-52490b80-2aa5-11e9-854f-4e106735053e.gif)

**Comment by Jacco** [comment]
@fsih its really a small change

**Comment by adroitwhiz** [comment]
@BryceLTaylor It looks like #833 fixed this and it just never got closed
