### ISSUE TITLE
Flickering when filling cat's leg with transparent

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#687]
### Expected Behavior
Probably no flickering

### Actual Behavior
The shape is hard to fill with transparent because it flickers when the mouse moves
![flickering](https://user-images.githubusercontent.com/2855464/45633898-06061c00-ba6f-11e8-99a9-4264136c8a4e.gif)

Scratch 2.0 flickers even more though
![flickering2](https://user-images.githubusercontent.com/2855464/45633939-1d450980-ba6f-11e8-8614-1bbcd20ca91a.gif)

### Steps to Reproduce
1. Set fill color to transparent
2. Hover over cat's front leg

### Operating System and Browser
Windows 10 Chrome

**Comment by thisandagain** [comment]
We are going to replace the cat. @carljbowman do you have a time when you would like to get this done?
