### ISSUE TITLE
In reshape tool, you often add a point when you mean to drag a point

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#691]
### Expected Behavior
You should mostly do what you expect to do

### Actual Behavior
I add points instead of dragging them all the time >:S maybe you shouldn't be able to make overlapping points.
![addpoint](https://user-images.githubusercontent.com/2855464/45781546-4e1f6d00-bc2e-11e8-8419-6f8606c83b60.gif)

### Steps to Reproduce
In the reshape tool, drag points around to make a shape

### Operating System and Browser
all

**Comment by adroitwhiz** [comment]
This was also mentioned as an issue [in the Advanced Topics forum](https://scratch.mit.edu/discuss/topic/381176/).
