### ISSUE TITLE
Outlines not respecting color on iPad safari

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#709]
From  @benjiwheeler 9/21
Issue #1: iPad safari: in the costume editor:
choose the arrow select tool
set fill to a non-transparent color
set outline size to 0
set outline color to a non-transparent color
click on the circle or rectangle tool
...the outline color will switch to transparent.

Issue #2: 
Add step 6 to the above: draw a circle or rect in the editor. 
Now keep repeating steps 1-6. You will notice that in the stage, some of the shapes appear with an outline of size 1!!

**Comment by BryceLTaylor** [comment]
Can't reproduce.  I think this was changed deliberately so you can't have a transparent stroke with a thickness > 0 or a non-transparent stroke with a stroke thickness = 0.
