### ISSUE TITLE
Keyboard Shortcuts - Phase 2

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-paint#711]
**Feedback**
Some addtional keyboard shortcuts were expected during recent playtests.

**Expected Shortcuts**
Listed with Mac modifier keys

Group: CMD + “g”
Ungroup: CMD + Shift + “g”
Cut: CMD + “x”

**Comment by mxmou** [comment]
This was fixed by #1133.

**Comment by carljbowman** [comment]
Thanks @mxmou for flagging this! 

Closing with fix by https://github.com/LLK/scratch-paint/pull/1133.
