### ISSUE TITLE
Eye dropper tool getting stuck

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-paint#713]
### Expected Behavior

Eye dropper tool should be successful in selecting a color.

### Actual Behavior

Eye dropper is getting stuck in this project: https://beta.scratch.mit.edu/#64636198 and shows the following error in the console:

```
raven.js:429 Uncaught TypeError: Cannot read property 'activate' of undefined
    at A.value (lib.min.js:135)
    at HTMLDocument.A (lib.min.js:1)
    at HTMLDocument.d (raven.js:425)
```

![color_picker_freezing](https://user-images.githubusercontent.com/1786240/46362991-c11de000-c63f-11e8-9d38-8ce73cd1af86.gif)

### Steps to Reproduce

1. Open the project above
2. Click on the "Levels" sprite
3. Switch to the costumes tab
4. Select the first costume
5. Select the eye dropper from the "Fill" dropdown menu
6. Try to select the pink square on the green rectangle on the left of the costume
7. Observe that the color picker is stuck open
8. Observe the error mentioned above in the console

**Comment by BryceLTaylor** [comment]
It appears that what is happening is that no tool is selected in the bitmap editor.  If you load a project with a bitmap sprite in it, select the bitmap sprite, then open the paint editor, you will notice that there is no tool selected in the paint editor.  You can, however, choose a color.

In the project linked above, you can see it on the "Monster1" sprite as well.
![bitmapnotool](https://user-images.githubusercontent.com/1088291/49038502-264b0900-f18b-11e8-8147-e8bd5232f855.png)
Note: no tool is selected.
Then if you use the eyedropper with no tool selected it freezes as shown above.

It's important that no tool was ever selected for this to work, which means the first sprite you open must be a bitmap sprite.  You might not see it if you have opened a vector sprite in the paint editor and then chosen a new project with file>upload.  It remembers the tool you had selected in the vector editor.  You can see it if you reload the page afterwards.

Another way to reproduce
1. Open the default project.
2. Open the paint editor with the cat selected
3. Convert the cat to bitmap
4. Download the project.
5. Reload the webpage (see above)
6. Choose File>upload from your computer
7. upload the project you just downloaded
8. Open the paint editor
note: see the bitmap cat sprite
note: no tool is selected
9. Select the fill color
10. Choose the eyedropper
11. Click somewhere on the cat
note: you see the same strange behavior from before

You can undo the frozen eyedropper by converting the image to vector, then click the eyedropper in the drop down twice.  Then you can convert back to bitmap.
Note: when the eyedropper becomes responsive the paintbrush tool is selected.

**Comment by fsih** [comment]
Duping to https://github.com/LLK/scratch-paint/issues/811
