### ISSUE TITLE
Non-breaking spaces render incorrectly in Marker font

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#725]
### Expected Behavior
In order to fix https://github.com/LLK/scratch-render/issues/292 , it may be necessary to replace spaces with non-breaking spaces

### Actual Behavior
Non-breaking spaces look the same as spaces in all of our fonts except Marker, which seems to map all sorts of characters incorrectly

![marker characters](https://user-images.githubusercontent.com/2855464/46979315-4fae4a80-d09f-11e8-84b5-5130aa1499c2.gif)

### Steps to Reproduce
Type some characters such as 
```
ÄËëÏïÖöÜü
    Ÿÿ   
        ††
```
into text edit in the Marker font and observe that they show up wrong

### Operating System and Browser
Windows 10 Chrome

**Comment by fsih** [comment]
![marker characters2](https://user-images.githubusercontent.com/2855464/46980510-c39e2200-d0a2-11e8-87ff-e86645a16cb7.gif)

**Comment by cwillisf** [comment]
Looks like it's not just the non-breaking space. These two text boxes have the same content:
![image](https://user-images.githubusercontent.com/7019101/47032456-45379380-d127-11e8-88a1-3c7ae81ca7f2.png)

**Comment by fsih** [comment]
@cwillisf and I also found that the font mapping seems to be correct when the font is used in other applications
