### ISSUE TITLE
Issue while attempting to fill a duplicated group

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-paint#728]
### Expected Behavior
- You should be able to use the fill tool on duplicated groups in a costume

### Actual Behavior
- The fill tool can cause the entirety of the group to disappear

### Steps to Reproduce
- https://drive.google.com/file/d/1bgLvfAyD2bN7gbM19q2U4lzDal1fpTxH/view?usp=sharing

**Comment by thisandagain** [comment]
@BryceLTaylor Could you put a priority on attempting to repro this?

/cc @fsih

**Comment by fsih** [comment]
@thisandagain is there any chance we can get the costume SVG? It looks like it's happening when they mouse over that hole in the middle.

**Comment by thisandagain** [comment]
@fsih Yup! I have requested it and will share once I hear back.

**Comment by thisandagain** [comment]
@fsih @BryceLTaylor Artwork from video: 
[Spaceship_V4 (1).svg.zip](https://github.com/LLK/scratch-paint/files/2496531/Spaceship_V4.1.svg.zip)

**Comment by thisandagain** [comment]
Details from user:
```
I'm running MacOS Mojave 10.4, and it first occurred in the most current Chrome build (70.~)
I then tried it in the most current safari browser and the same thing occurred.
Next, I tried my linux laptop using Chromium. Same thing.

Yes that's correct. I only noticed the glitch occur while working with the Spaceship sprite (specifically when it's duplicated).
```

**Comment by BryceLTaylor** [comment]
Huh.  I got into a situation where when dragging the bucket tool over the spaceship the eyes disappeared and the paint editor froze.  Switching sprites or costumes didn't change what was in the paint editor, but it would affect the stage.  

There were errors in the console:
![spaceship error](https://user-images.githubusercontent.com/1088291/47301396-cd68dd80-d5ec-11e8-927f-2ba67003541c.png)

I am having trouble reproducing it.  I'll keep working on that.  This was on Mac Chrome.

**Comment by BryceLTaylor** [comment]
In that state, it in fact DOES allow you to interact with objects in the paint editor, you just can't see the changes in the editor.  Still haven't reproduced yet.

**Comment by BryceLTaylor** [comment]
I've reproduced it a few times now, but I don't have reliable repro steps.  It always seems to happen immediately after mousing over a hole (a mask?) in the svg with the fill tool selected.  But it isn't every time you do this.  I haven't figured out what the steps you need  to do to make that happen. 

It may have something to do with adding a backdrop and it may have something to do with resizing shortly before using the fill tool.

**Comment by BryceLTaylor** [comment]
I don't think it has anything to do with duplication.

I opened the SVG in a text editor and it definitely has a few masks in it, which might be causing some problems.
