### ISSUE TITLE
Certain costumes glitch in the editor

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-paint#729]
[icon.zip](https://github.com/LLK/scratch-gui/files/2504570/icon.zip)

### Expected Behavior

The costume editor should be able to handle any image generated by scratch 2.0

### Actual Behavior

The editor behaves oddly when loading certain files.
I don't know what causes these files in particular to misbehave.

### Steps to Reproduce

The file I have attached loads as intended in Scratch 2.0, but causes issues in scratch 3.0

This issue seems to only affect the costume editor and work fine if directly loaded from a .sb2 project.

### Operating System and Browser

Windows 7, Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

---
Moved from LLK/scratch-gui#3462
/cc @Robomandude

**Comment by fsih** [comment]
Uploading the asset (as a sprite only, it works fine if uploaded as a costume) causes Scratch to get a 404 from the asset server. Here is the stack trace.

VM3268:1 GET https://assets.scratch.mit.edu/internalapi/asset/0112e41fbfe91183528fdaf6308db74e.svg/get/ 404
(anonymous) @ VM3268:1
_createXHR @ index.js:224
createXHR @ index.js:52
Nets @ index.js:23
tryNextSource @ WebHelper.js:100
(anonymous) @ WebHelper.js:118
load @ WebHelper.js:72
tryNextHelper @ ScratchStorage.js:164
(anonymous) @ ScratchStorage.js:168
Promise.then (async)
tryNextHelper @ ScratchStorage.js:164
(anonymous) @ ScratchStorage.js:198
load @ ScratchStorage.js:160
loadCostume @ load-costume.js:166
(anonymous) @ sb3.js:849
Promise.then (async)
(anonymous) @ sb3.js:846
parseScratchObject @ sb3.js:823
(anonymous) @ sb3.js:1020
deserialize @ sb3.js:1019
_addSprite3 @ virtual-machine.js:541
(anonymous) @ virtual-machine.js:505
Promise.then (async)
addSprite @ virtual-machine.js:498
handleNewSprite @ target-pane.jsx:135
wrapper @ index.js:550
(anonymous) @ file-uploader.js:216
addCostumeFromBuffer @ file-uploader.js:127
costumeUpload @ file-uploader.js:135
spriteUpload @ file-uploader.js:198
(anonymous) @ target-pane.jsx:145
reader.onload @ file-uploader.js:33
load (async)
handleFileUpload @ file-uploader.js:25
handleSpriteUpload @ target-pane.jsx:144
wrapper @ index.js:550
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:452
executeDispatch @ react-dom.development.js:836
executeDispatchesInOrder @ react-dom.development.js:858
executeDispatchesAndRelease @ react-dom.development.js:956
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:967
forEachAccumulated @ react-dom.development.js:935
processEventQueue @ react-dom.development.js:1112
runEventQueueInBatch @ react-dom.development.js:3607
handleTopLevel @ react-dom.development.js:3616
handleTopLevelImpl @ react-dom.development.js:3347
batchedUpdates @ react-dom.development.js:11082
batchedUpdates @ react-dom.development.js:2330
dispatchEvent @ react-dom.development.js:3421
minilog.js:17 vm  TypeError: Cannot read property 'assetId' of null
    at loadCostumeFromAsset (load-costume.js:120)
    at load-costume.js:171
./node_modules/minilog/lib/web/formatters/minilog.js.logger.write @ minilog.js:17
onItem @ transform.js:31
emit @ index.js:26
./node_modules/minilog/lib/common/filter.js.Filter.write @ filter.js:52
onItem @ transform.js:31
emit @ index.js:26
./node_modules/minilog/lib/common/transform.js.Transform.write @ transform.js:15
o.error @ minilog.js:12
(anonymous) @ load-costume.js:174
Promise.catch (async)
loadCostume @ load-costume.js:172
(anonymous) @ sb3.js:849
Promise.then (async)
(anonymous) @ sb3.js:846
parseScratchObject @ sb3.js:823
(anonymous) @ sb3.js:1020
deserialize @ sb3.js:1019
_addSprite3 @ virtual-machine.js:541
(anonymous) @ virtual-machine.js:505
Promise.then (async)
addSprite @ virtual-machine.js:498
handleNewSprite @ target-pane.jsx:135
wrapper @ index.js:550
(anonymous) @ file-uploader.js:216
addCostumeFromBuffer @ file-uploader.js:127
costumeUpload @ file-uploader.js:135
spriteUpload @ file-uploader.js:198
(anonymous) @ target-pane.jsx:145
reader.onload @ file-uploader.js:33
load (async)
handleFileUpload @ file-uploader.js:25
handleSpriteUpload @ target-pane.jsx:144
wrapper @ index.js:550
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:452
executeDispatch @ react-dom.development.js:836
executeDispatchesInOrder @ react-dom.development.js:858
executeDispatchesAndRelease @ react-dom.development.js:956
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:967
forEachAccumulated @ react-dom.development.js:935
processEventQueue @ react-dom.development.js:1112
runEventQueueInBatch @ react-dom.development.js:3607
handleTopLevel @ react-dom.development.js:3616
handleTopLevelImpl @ react-dom.development.js:3347
batchedUpdates @ react-dom.development.js:11082
batchedUpdates @ react-dom.development.js:2330
dispatchEvent @ react-dom.development.js:3421

**Comment by fsih** [comment]
In load-costume.js, in loadCostume, the costume asset returned by runtime.storage.load is null.
![image 5](https://user-images.githubusercontent.com/2855464/47679840-9752cd00-db9b-11e8-88f3-e6b9d1411bcf.png)

**Comment by fsih** [comment]
@rschamp is it possible this is a side effect of the changes to load costume recently?

**Comment by rschamp** [comment]
Yes it sure does look like an issue with handling absent assets in the VM.

**Comment by Robomandude** [comment]
I don't know what you guys did, but this issue seems to be largely resolved now.

The only problem I can spot is when you switch to the costume from another in the editor, part of the costume initially displays at the wrong location before snapping into place less than a second later.

Image of before and after the 'snapping'
![wronglocation](https://user-images.githubusercontent.com/14086052/47957448-0194b480-df84-11e8-9fb3-372abd85b600.png)

Steps to reproduce:
1: load the icon costume into the project.
2:Have any other costume also loaded into the project
3:Select the other costume
4:select the icon costume.
The effect lasts around 1/10 of a second each time it is triggered.

Doing any modifications to the costume, even if later undone, stops the snapping effect and replaces it with another one.
It will then not display part of the costume for a moment before displaying as normal.
![hidden](https://user-images.githubusercontent.com/14086052/47957505-d2327780-df84-11e8-9eec-6128e152f42f.png)

I'm pretty sure I remember the costumes did this snapping thing before but they would snap to the corner of the editor.  It was difficult to describe so I simply said it "glitched" the editor.  Because of this I believe this is the same issue.

Once again the issue is largely resolved and this is a great improvement over before.



*edit*
now that I think about it, the part of the costume that is affected is a bitmap image imported into the vector costume.

**Comment by BryceLTaylor** [comment]
This appears to behave just fine in chrome on mac.  On Safari on the other hand...

Uploading it as a sprite causes nothing to appear on the stage.  

If you open the costume it appears, but without the text.

The sprite uploaded version says it's 16x7

The costume uploaded version says it's 32x14

neither one shows text in the thumbnail

If you change select the sprite uploaded one in the costume editor but leave it almost exactly the same size as it was, the sprite appears on the stage and the text appears on the stage and in the thumbnail.  The dimensions also change to ~27x16 (approximately doubles in width)

If you change the size of the costume uploaded one in the paint editor but leave it almost exactly the same size, the text appears on the stage and in the thumbnail.  The size becomes ~26x16

**Comment by thisandagain** [comment]
@BryceLTaylor Thanks. Can you open a new issue for this behavior you are seeing in Safari. I believe this issue should be closed in favor of your (more specific) description.

**Comment by BryceLTaylor** [comment]
Moved it to https://github.com/LLK/scratch-paint/issues/782 .  Closing this one.
