### ISSUE TITLE
Add "add costume by paint editor" button to GUI

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#75]

**Comment by fsih** [comment]
I think I need a new asset for this

**Comment by carljbowman** [comment]
Sketch:
Include "Add Blank Costume" button above the "Add Costume from Library" button
![selection tool - 1024x768](https://user-images.githubusercontent.com/3409578/32246186-8c5f9366-be54-11e7-8411-d146af1cf052.png)


Asset:
[asset.zip](https://github.com/LLK/scratch-paint/files/1432096/asset.zip)

**Comment by mewtaylor** [comment]
Implemented in https://github.com/LLK/scratch-gui/pull/1137
