### ISSUE TITLE
Uploaded SVG doesn't appear on stage

### ISSUE THREAD

**Issue by knandersen** [LLK/scratch-paint#753]
### Expected Behavior

When I upload an SVG as a costume using Firefox, I expect it to appear on the stage.

### Actual Behavior

When I upload an SVG as a costume using Firefox, it doesn't appear on stage, unless I make a change to the costume. Also tested this using Safari 12.0, where the expected behavior occurs, so it could just be a Firefox issue!

![vectorbug2](https://user-images.githubusercontent.com/24595727/47676484-214a6800-db93-11e8-8dde-e3f7d6cd5571.gif)

### Steps to Reproduce

1. Upload an SVG in the costume editor using Firefox
2. Observe missing costume on stage
3. Make change to uploaded SVG in the costume editor
4. Costume appears on stage

### Operating System and Browser

MacOS 10.14 using Firefox 63.0 / Safari 12.0

**Comment by knandersen** [comment]
another interesting to observe is that the size of the costume changes when a change is made (300x300px to 116x118 just by moving the shape a few pixels)

**Comment by fsih** [comment]
@knandersen can you upload the specific SVG? I seem to be able to upload SVGs in Firefox

**Comment by knandersen** [comment]
@fsih sure! Here you go:
[vectorbug3.svg.zip](https://github.com/LLK/scratch-paint/files/2531269/vectorbug3.svg.zip)

**Comment by knandersen** [comment]
Maybe useful to know that it's an SVG exported from Adobe Illustrator (SVG version 1.1)
