### ISSUE TITLE
Uploaded SVG displaces when changed

### ISSUE THREAD

**Issue by knandersen** [LLK/scratch-paint#754]
### Expected Behavior

Uploading a complex SVG and changing a fill color would not displace the entire SVG.

### Actual Behavior

Uploading a complex SVG, duplicating the costume, and then changing a single property of the duplicated costume, displaces the entire SVG slightly. Not able to reproduce using just a few basic shapes, but stumbled upon this when working with multiple shapes that are part of one SVG.

![bug3](https://user-images.githubusercontent.com/24595727/47676412-f6601400-db92-11e8-952b-d8a49325e7ab.gif)

### Steps to Reproduce

SVG exported from Adobe Illustrator with settings:
SVG Profile: SVG 1.1
Type: SVG
Image Location: Link

1. Upload an SVG as a costume
2. Duplicate costume
3. Select part of the SVG and change, for example, the fill.
4. The entire duplicated SVG will displace

### Operating System and Browser

MacOS 10.14 / Firefox 63

**Comment by fsih** [comment]
This should be fixed on develop (https://llk.github.io/scratch-gui/develop/)
