### ISSUE TITLE
Line breaks are not retained when text is rendered to stage

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-paint#763]
### Expected Behavior
Text with multiple line breaks should render the same in the paint editor and stage.

### Actual Behavior
Text is shown with line breaks collapsed

### Steps to Reproduce
- Load https://beta.scratch.mit.edu/#203349676
- Navigate to sprite one, costume 3 ("Slide 2")

### Reference
![image](https://user-images.githubusercontent.com/747641/48355712-a9843f00-e662-11e8-8e4b-feb4eaaa1f2a.png)
![image](https://user-images.githubusercontent.com/747641/48378609-3b11a200-e69f-11e8-9462-5a44f42af8be.png)

### Minimal Test Reproduction
https://scratch.mit.edu/projects/261570023
https://beta.scratch.mit.edu/#261570023

### Operating System and Browser
Mac OS 10.14.1 | Chrome Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by thisandagain** [comment]
@fsih @BryceLTaylor I'm not sure if this should be in paint or render, so I left it here from investigation.

**Comment by fsih** [comment]
Duping to https://github.com/LLK/scratch-render/issues/292
