### ISSUE TITLE
Should we try to cap the stroke lower?

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#768]
Should we try to cap the stroke lower? Weird things happen if you go over 3 digit values… @kathymakes 
![image15](https://user-images.githubusercontent.com/1088291/48020513-1304ca80-e104-11e8-87c2-bcfb53024116.gif)

**Comment by thisandagain** [comment]
@fsih @carljbowman @kathymakes Seems like capping at 100 would make sense.

**Comment by fsih** [comment]
Some weird stuff can still happen at 100, but well, I guess it's less weird.
![image](https://user-images.githubusercontent.com/2855464/49965274-bf4b8500-feea-11e8-8ebe-e9e6d761319a.png)
If you look at the stage, for some reason that's how SVG renders really thick strokes...
