### ISSUE TITLE
Missing "appropriate loader" in use as library

### ISSUE THREAD

**Issue by apzimmer** [LLK/scratch-paint#773]
### Expected Behavior

Hello,

I'm excited to try scratch-paint as a library in a project I'm working on. I keep running up against the following error:

### Actual Behavior

```
Module parse failed: Unexpected token (292:12)
You may need an appropriate loader to handle this file type.
|     render () {
|         return (
>             <PaintEditorComponent
|                 canRedo={this.props.shouldShowRedo}
|                 canUndo={this.props.shouldShowUndo}

```
### Steps to Reproduce

Create a blank react project with e.g. CRA, npm install scratch-paint (and peer dependencies, which need to be installed manually). Use this for app.js:

```
import React, { Component } from "react";
import PaintEditor from "scratch-paint";

class App extends Component {
  render() {
    return <PaintEditor imageFormat="svg" rtl={true | false} />;
  }
}

export default App;

```
### Operating System and Browser

NPM 6.4.1

**Comment by thisandagain** [comment]
@apzimmer This looks like a webpack configuration issue. Are you able to load other react components?

**Comment by apzimmer** [comment]
Yep, webpack issue. Thanks!

**Comment by vkochatkov** [comment]
@apzimmer how did you fix this issue? what webpack config did you change?
