### ISSUE TITLE
SVGs uploaded as costume v. sprite comes in at different sizes

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-paint#777]
### Expected Behavior

If you import an image as a sprite it should be the same size as it would if you imported it as a costume.

### Actual Behavior

The image comes in much larger as a costume than it does as a sprite.
![itsfine](https://user-images.githubusercontent.com/1088291/47881462-94a2e280-ddfc-11e8-9d2d-39dff0ff650a.gif)

### Steps to Reproduce

Hover over the new sprite thermometer
Choose upload from file
choose an svg
Note: the new sprite is tiny on the stage
Open the costume editor
choose upload a new costume
choose the same svg
Note: the sprite now appears bigger on the stage, but the new costume is the same size in the paint editor.
select the first costume
edit it slightly
Note: the sprite gets larger on the stage
edit the second costume:
note: it stays the same size

### Operating System and Browser

Mac Chrome

---
Moved from LLK/scratch-gui#3608
/cc @BryceLTaylor @rschamp @cwillisf @fsih @paulkaplan

**Comment by kchadha** [comment]
Closing because I don't think this is actually a scratch-paint issue.

**Comment by fsih** [comment]
This might have already been fixed by https://github.com/LLK/scratch-svg-renderer/pull/60
