### ISSUE TITLE
Paint editor broken - "Cannot read property 'en' of undefined"

### ISSUE THREAD

**Issue by epicfaace** [LLK/scratch-paint#784]
### Expected Behavior

It should load properly

### Actual Behavior

Error - Cannot read property 'en' of undefined

### Steps to Reproduce
 Go to https://llk.github.io/scratch-paint/

### Operating System and Browser
Mac OS, Google Chrome

**Comment by fsih** [comment]
This issue is breaking the paint editor playground. It's making it hard for some contributors who don't have gui integration set up to develop. Therefore I'm moving it to January.

**Comment by epicfaace** [comment]
This has been resolved
