### ISSUE TITLE
Stroke widths should scale when shapes are transformed

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#80]
Currently they don't scale, which makes the shape end up with weird proportions.

![scalestrokewidth](https://user-images.githubusercontent.com/2855464/31793926-958c7342-b4ee-11e7-9245-f664cf3c4213.gif)

**Comment by fsih** [comment]
It's arguable that they shouldn't scale. For instance if you want to resize parts of the scratch cat, it looks better if all the stroke sizes remain consistent rather than different parts having slightly different outline widths.

**Comment by Mr-Dave2** [comment]
It's probably better this way for new drawings but could be a problem for people wanting to remix costumes/backdrops that have parts that have been 'thickened'.    When the costume is opened in the Scratch 3.0 paint editor the parts will be deflated.  (and I just saw, somewhere, an issue with someone's deflated speech balloon).

**Comment by fsih** [comment]
It shouldn't affect imported costumes, only how the thickness changes when you use the select tool. I think the deflated speech balloon bug was caused by a different bug.

**Comment by fsih** [comment]
@Mr-Dave2 I filed a new issue for that import bug, https://github.com/LLK/scratch-paint/issues/381

**Comment by fsih** [comment]
Duping to https://github.com/LLK/scratch-paint/issues/812
