### ISSUE TITLE
Text insertion cursor can extend past edge of paint area

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-paint#806]
### Expected Behavior

Text cursor should stay inside paint canvas area

### Actual Behavior
 
THIS
![cursor blink](https://user-images.githubusercontent.com/3431616/50309978-ab65cd00-046e-11e9-85b1-6739c61b474a.gif)

### Steps to Reproduce

Zoom in in paint editor a lot
choose text tool
click near top of canvas
!!!!!

### Operating System and Browser

Mac Mojave, Chrome 78-something current

**Comment by fsih** [comment]
dupe of https://github.com/LLK/scratch-paint/issues/641
