### ISSUE TITLE
Paint Editor Tools should not be not selected by default

### ISSUE THREAD

**Issue by ChampikaF** [LLK/scratch-paint#811]
### Expected Behavior

No paint editor tools should not be selected by default 

### Actual Behavior

When clicking around on sprites while in the costumes tab the tool that's selected switches automatically creating a confusing experience because the options at the top of the paint editor change. 

### Steps to Reproduce
When opening an existing project (e.g Animate an Adventure Game) if you switch to "Costumes" tab no tools are selected for "Garnet". If you click on "Jake" no tool is selected and you see the flip options in the paint editor. If you then select "KO" from the sprites, the paintbrush tool is automatically selected. If you now switch to "Jake" the "paintbrush" is selected and you lose the options at the top.

**Comment by fsih** [comment]
This can be reproed on dev server at http://localhost:8601/#249143200

**Comment by fsih** [comment]
(Edit: it seems it's not relevant)
There's an error when opening the animate an adventure game project, not sure if it's related
lib.min.js:18377 Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `LibraryComponent`. See https://fb.me/react-warning-keys for more information.
    in InjectIntl(LibraryItem) (created by LibraryComponent)
    in LibraryComponent (created by InjectIntl(LibraryComponent))
    in InjectIntl(LibraryComponent) (created by TipsLibrary)
    in TipsLibrary (created by Connect(TipsLibrary))
    in Connect(TipsLibrary) (created by InjectIntl(Connect(TipsLibrary)))
    in InjectIntl(Connect(TipsLibrary)) (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in MediaQuery (created by GUIComponent)
    in GUIComponent (created by Connect(GUIComponent))
    in Connect(GUIComponent) (created by InjectIntl(Connect(GUIComponent)))
    in InjectIntl(Connect(GUIComponent)) (created by GUI)
    in GUI (created by Connect(GUI))
    in Connect(GUI) (created by InjectIntl(Connect(GUI)))
    in InjectIntl(Connect(GUI)) (created by CloudManager)
    in CloudManager (created by Connect(CloudManager))
    in Connect(CloudManager) (created by VMManager)
    in VMManager (created by Connect(VMManager))
    in Connect(VMManager) (created by VMListener)
    in VMListener (created by Connect(VMListener))
    in Connect(VMListener) (created by ProjectSaverComponent)
    in ProjectSaverComponent (created by Connect(ProjectSaverComponent))
    in Connect(ProjectSaverComponent) (created by ProjectFetcherComponent)
    in ProjectFetcherComponent (created by Connect(ProjectFetcherComponent))
    in Connect(ProjectFetcherComponent) (created by InjectIntl(Connect(ProjectFetcherComponent)))
    in InjectIntl(Connect(ProjectFetcherComponent)) (created by QueryParserComponent)
    in QueryParserComponent (created by Connect(QueryParserComponent))
    in Connect(QueryParserComponent) (created by FontLoaderComponent)
    in FontLoaderComponent (created by Connect(FontLoaderComponent))
    in Connect(FontLoaderComponent) (created by ErrorBoundaryWrapper)
    in ErrorBoundary (created by Connect(ErrorBoundary))
    in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)
    in ErrorBoundaryWrapper (created by LocalizationWrapper)
    in IntlProvider (created by Connect(IntlProvider))
    in Connect(IntlProvider) (created by LocalizationWrapper)
    in LocalizationWrapper (created by Connect(LocalizationWrapper))
    in Connect(LocalizationWrapper) (created by TitledComponent)
    in TitledComponent (created by HashParserComponent)
    in HashParserComponent (created by Connect(HashParserComponent))
    in Connect(HashParserComponent) (created by AppStateWrapper)
    in IntlProvider (created by Connect(IntlProvider))
    in Connect(IntlProvider) (created by AppStateWrapper)
    in Provider (created by AppStateWrapper)
    in AppStateWrapper
