### ISSUE TITLE
Should filling the background of a vector costume do something?

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-paint#824]
I've noticed a few Scratchers have been surprised that they can't as easily make the background of the stage a different color anymore. That's because in 3.0, costumes and backdrops default to being vector costumes, rather than bitmap. So when users try to use the fill bucket to set the background color of the stage, they're just clicking on empty space, and there's no effect! As a workaround, users either need to recognize that they are in vector mode and switch to bitmap, or create a rectangle filling the whole screen and set it to the right color.

I'm not sure what the best solution is here, but it's worth considering. Perhaps clicking fill on the background of a vector costume should automatically create a rectangle with exactly the right dimensions? I wonder if this rectangle would surprise users, since it would probably be able to be dragged around and resized like any normal rectangle. At the same time, I don't think automatically converting the vector costume (even if it's 100% empty) to bitmap seems very intuitive!

**Comment by thisandagain** [comment]
Thanks @towerofnix! This is something @fsih @carljbowman and I have discussed as well.

**Comment by towerofnix** [comment]
Apparently this is a help wanted feature already: #250. This issue (824) is labelled needs-discussion now; is that feature still wanted, per the earlier discussion that got it labelled help-wanted?

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-paint/issues/250
