### ISSUE TITLE
Show center crosshair on top of artwork

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-paint#845]
Feature request from Twitter, that I've heard asked for elsewhere:

“Alternate solution for allowing user to set a sprite's center: have the cross hair that shows the center to show on top of the custome in the editor. That way we can actually see the center. Pleeeeease!!!”

Maybe this could be shown only while moving a costume, so it's more clear that it's not a visible part of the costume itself?

This would help in centering costumes, without requiring users to just eyeball it.

**Comment by BryceLTaylor** [comment]
This was recently addressed
