### ISSUE TITLE
Start with a bitmap image, and click flip will make image disappear

### ISSUE THREAD

**Issue by JinXJinX** [LLK/scratch-paint#852]
### Expected Behavior

image flip when I click flip

### Actual Behavior

Start with a bitmap image, and click flip will make image disappear

### Steps to Reproduce

1. open this link https://scratch.mit.edu/projects/316589791/editor/
2. click "stage" at the bottom right
3. click "Backdrops" at the top left. you will see no mode is selected.
4. click "flip horizontal" or "flip vertical"
5. the backdrop will disappear in the right canvas

![bitmap_backdrop on Scratch - Edited](https://user-images.githubusercontent.com/12160296/59366256-0f739a80-8d08-11e9-8eb4-b06fdcdc291c.gif)
 

### Operating System and Browser

Mac OS 10.14 Chrome 75

### A Little More

in the `reducers/modes.js`, initialState is `Modes.SELECT`. However, If starts with bitmap format, the initial state should be `Modes.BIT_SELECT`

**Comment by fsih** [comment]
Duping to https://github.com/LLK/scratch-paint/issues/811
