### ISSUE TITLE
NPM package doesn't have /dist folder in it

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-paint#886]
Looks like we changed something recently that stopped publishing the `/dist` folder to npm, which is causing builds to fail upstream e.g. in scratch-gui.

(stub issue to keep track of the investigation @fsih  has been doing)

**Comment by fsih** [comment]
After https://github.com/LLK/scratch-paint/pull/888, it's fixed!

https://unpkg.io/scratch-paint@0.2.0-prerelease.20190807143414/dist/
