### ISSUE TITLE
Clicking on the Eraser crash the Paint

### ISSUE THREAD

**Issue by tadanet3** [LLK/scratch-paint#896]
### Expected Behavior

Clicking on the eraser doesn't crash the paint.

### Actual Behavior

Clicking on the Eraser crash the Paint.

### Steps to Reproduce
(this requires a _blank costume_)
1.Click Sprite Paint
  Selected Costumes tab.
2.Click Convert to Bitmap
  Changed Bitmap mode.
3.Click Select Button
  Chenged Select mode.
4.Select any area
5.Click Eraser

### Operating System and Browser

Ubuntu 19.04 firefox 68.0.1 64bit

**Comment by fsih** [comment]
dupe of https://github.com/LLK/scratch-paint/issues/859
