### ISSUE TITLE
Reshape tool should not move shape when shape dragged

### ISSUE THREAD

**Issue by Ascor8522** [LLK/scratch-paint#899]
### Expected Behavior

In vector mode,
when the reshape tool is selected and
the inside of the selected shape is dragged,
the selected shape should not be moved.

This is a task for the selecting tool, not for the reshaping tool.

### Actual Behavior

The reshape tool moves the selected shape when dragged.
It should bring up a selection box to select the nodes to edit.

### Steps to Reproduce

1. Open the Scratch editor (online or offline).
2. Select any vector costume.
3. Select the reshaper tool.
4. Select a shape in the costume.
5. Drag the shape around (do not select handles or the outline of the shape, drag from any other place, like the middle)

![Picture depicting the actual behavior](https://user-images.githubusercontent.com/17651422/63180874-6fabf300-c04f-11e9-941b-4e945e3bbf42.gif)

**Comment by fsih** [comment]
This is working as intended. Sorry that the tool name is confusing :/
Is there something you are trying to do that isn't working because you can move shapes in reshape?

**Comment by Ascor8522** [comment]
Sorry, but I think you didn't get my point.

The reshape tool (the one with the arrow and the node, the one i used in the gif above) should not be  able to move an entire shape.
It should be used :
- when dragged, to select the nodes to edit (a select box should appear, not working)
- when dragging a node, to edit the shape (working as intended)

but not to move the shape.

For that, only the selecting tool (1st one, the one with the arrow) should be used, since it's the one used to move the whole (or parts, shapes) of the costume.

See the intended behavior in other design softwares below (Inkscape, Affinity Designer)...
![Intended behavior in Inkscape](https://user-images.githubusercontent.com/17651422/63456005-4f64a580-c44e-11e9-9f1c-e8c96ba72d39.gif)
![Intended behavior in Affinity Designer](https://user-images.githubusercontent.com/17651422/63456004-4f64a580-c44e-11e9-8bab-a8d106b98b27.gif)
