### ISSUE TITLE
Set an undo stack size limit

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#90]

**Comment by thisandagain** [comment]
If we have learned anything over the past 10 years of working on Scratch it is that if you don't set a limit then someone will do something crazy and either crash Scratch (when this stuff is server-side) or get very sad and crash their client. Yes, we should set a maximum undo stack size. 😉 

How would you feel about 99 as a limit?

**Comment by thisandagain** [comment]
For reference, the default size of the undo stack in Adobe Photoshop is 50.
