### ISSUE TITLE
On selecting bucket, artwork disappears, and paint enters broken state

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-paint#907]
In this project, https://scratch.mit.edu/projects/326277982/ , it's possible to get the paint area into a broken state.

![Aug-29-2019 20-54-56](https://user-images.githubusercontent.com/3431616/64023609-afbaad80-cb06-11e9-8c8f-27945ceea2d8.gif)

### Steps to reproduce

Unfortunately I couldn't reproduce this from scratch, only by using my stripped down project (see above)

1. go to the sprite's first costume
2. select paint tool
3. mouse over the paint editor
4. some artwork in the paint editor will disappear.

Also try:

1. go to the sprite's first costume
2. select paint tool
3. mouse over the paint editor
4. some artwork in the paint editor will disappear.
5. click on the other costume in that sprite
6. the outline of Dot the dog will persist in the paint editor

Also try:

1. go to the sprite's first costume
2. select paint tool
3. mouse over the paint editor
4. some artwork in the paint editor will disappear.
5. click on the code tab, and back on the costumes tab
6. the paint editor will fail to render

### System/browser

Current MacOS 10.14.5, current Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by fsih** [comment]
The console is pointing to line https://github.com/LLK/paper.js/blob/develop/src/path/Path.js#L2320

paper-full.js:9153 Uncaught TypeError: Failed to execute 'fill' on 'CanvasRenderingContext2D': The provided value 'null' is not a valid enum value of type CanvasFillRule.
    at Path._draw (paper-full.js:9153)
    at Path.draw (paper-full.js:4519)
    at Layer._draw (paper-full.js:4705)
    at Layer.draw (paper-full.js:4519)
    at Project.draw (paper-full.js:2910)
    at CanvasView.update (paper-full.js:13248)
    at Array.<anonymous> (paper-full.js:12583)
    at handleCallbacks (paper-full.js:12416)

**Comment by fsih** [comment]
The issue is caused by the property `fill-rule="none"` in the SVG. `fill-rule` should only be defined as `"nonzero" `or `"evenodd"`
[d3c653e6eadfaeeb00e124c51261bd8e.svg.zip](https://github.com/LLK/scratch-paint/files/3560757/d3c653e6eadfaeeb00e124c51261bd8e.svg.zip)

**Comment by fsih** [comment]
The original dot asset doesn't have `fill-rule="none"`, maybe something got corrupted in the export process?
[06d70d5de0e25f97c1c606e513ab019c.svg.zip](https://github.com/LLK/scratch-paint/files/3560781/06d70d5de0e25f97c1c606e513ab019c.svg.zip)

**Comment by apple502j** [comment]
@fsih repro: https://scratch.mit.edu/discuss/topic/401269/
It happened to me using dot-c too, sad dog :( 
@adroitwhiz any plans for the PR?
