### ISSUE TITLE
Marker font doesn't print german umlauts

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-paint#911]
### Expected Behavior

If a German keyboard is used, typing the keys should put the expected symbols into text fields in the paint editor in all fonts.

### Actual Behavior

The Umlaut characters put the wrong symbols into the paint editor while in the Marker font.
![Screen Shot 2019-09-30 at 3 40 37 PM](https://user-images.githubusercontent.com/1088291/65910554-f109db80-e398-11e9-862b-971c05c542d3.png)

### Steps to Reproduce

Open a new project
Switch to the paint editor
Switch your keyboard to a german keyboard in system settings
Select the text tool
Type all of the keys on the keyboard using the sans serif font
Note: the keys match those of a german keyboard
Switch to the marker font
Type all of the keys on the keyboard again into a second text box
Note: most of the umlauted characters (except for ä) appear as the wrong symbol and the ä appears in the wrong font.
hold shift and type all of the letters
Note: none of the umlauted letters appear correctly
![Screen Shot 2019-09-30 at 3 49 58 PM](https://user-images.githubusercontent.com/1088291/65911082-02071c80-e39a-11e9-93e9-0167040de406.png)

### Operating System and Browser

Mac Chrome

**Comment by fsih** [comment]
Related to https://github.com/LLK/scratch-paint/issues/725
