### ISSUE TITLE
Converting to bitmap/vector makes mouse sync off in stretchy paint

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#955]
Converting to bitmap or vector changes the canvas size slightly, and if you switch to the brush tool, you will notice it doesn't precisely follow your mouse pointer anymore in the lower right corner.

**Comment by adroitwhiz** [comment]
This is a guess since the stretchy-paint branch isn't public, but are you applying a border to the Paper.js `<canvas>` element via CSS? This may be something similar to https://github.com/LLK/scratch-gui/pull/4232

**Comment by fsih** [comment]
Thanks for the tip! I think it's because the toolbar at the top is a
different height in the bitmap vs vector paint editor. The source for
stretchy-paint lives here:
https://github.com/LLK/scratch-paint/compare/develop...fsih:fillSpace?expand=1
