### ISSUE TITLE
Disable highlighting of tool icons and text 

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-paint#98]
<img width="701" alt="screen shot 2017-10-25 at 12 18 01 pm" src="https://user-images.githubusercontent.com/3409578/32010056-bdb8b0da-b97e-11e7-8681-febdf1e32709.png">

We should disable the ability to highlight.

**Comment by paulkaplan** [comment]
Yup, we do this in GUI for everything, i believe the css property is `user-select: none`
