### ISSUE TITLE
Logitech SetPoint Firefox extension causes the scroll wheel to break the paint editor

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-paint#986]
### Expected Behavior

Scrolling should work in the paint editor

### Actual Behavior

When using the [Logitech SetPoint/Smooth Scrolling extension](https://addons.mozilla.org/en-US/firefox/addon/logitechsmoothscrolling/) in Firefox, using the scroll wheel to scroll the paint editor view crashes paper.js, putting the paint editor into a buggy/non-interactible state.

### Steps to Reproduce

1. Install the Logitech Smooth Scrolling extension in Firefox (the Chrome extension does not appear to cause the issue)
2. Open the paint editor
3. Scroll the paint editor view using the mouse scroll wheel

### Operating System and Browser

Firefox on Windows (possibly other OSes)

**Comment by adroitwhiz** [comment]
It appears that `wheel` events created by the SetPoint extension lack the `deltaX` and `deltaY` properties. The Chrome version of the extension doesn't capture `wheel` events, which is why this only occurs on Firefox.

**Comment by rschamp** [comment]
Since the extension is breaking the wheel events, it's not something we're going to address on our side.
