### ISSUE TITLE
Undo/Redo should not be reversed in RTL languages

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-paint#987]
### Expected Behavior

In general things associated with time still go left-to-right in RTL languages. Since Undo/Redo are "time" related, they should stay in their usual orientation (Undo on the left, arrow pointing left/Redo on the right, arrow pointing right).

### Actual Behavior

Position and arrow direction is reversed in RTL langauges.

### Steps to Reproduce

Switch to Hebrew or Persian (Farsi).

Note, this was reported by a Persian speaker. We should verify that the direction makes sense for other RTL languages (e.g. Hebrew).

**Comment by Jacco** [comment]
@fsih I think I fixed this one :-) See PR

**Comment by chrisgarrity** [comment]
On further investigation this doesn't appear to be the convention for RTL UI. I tried using Google docs in both Hebrew and Persian. In both cases the undo/redo buttons in the toolbar were mirrored. I think Scratch should continue to use the mirrored convention.

**Comment by Jacco** [comment]
@chrisgarrity Just to be sure we're talking about the same thing. This is also Google docs:

![undo redo](https://user-images.githubusercontent.com/1318341/84387985-1faca700-abf4-11ea-9e92-d414079add60.gif)

Where command-Z is undo. Its confusing :-)

**Comment by Jacco** [comment]
And here is playground in RTL:

![undo redo 2](https://user-images.githubusercontent.com/1318341/84388678-47e8d580-abf5-11ea-9679-8264bb2146b7.gif)

**Comment by chrisgarrity** [comment]
I'm not sure why it's not reversed in the playground, but it's definitely correct in Scratch itself. Undo is on the right as expected:
![paint-rtl](https://user-images.githubusercontent.com/399209/84775990-c1921200-afad-11ea-9736-03ae5e634879.gif)

**Comment by fsih** [comment]
@chrisgarrity I think Jacco was probably sharing a gif of the PR change

**Comment by Jacco** [comment]
@chrisgarrity @fsih oh darn, thats silly of me :-) Sorry for the confusion.
